;Generated by PB Type Library Importer Version: 1.0
;mshtml.tlb
;mshtml_iid_str.pbi

;- IID_IHTMLEventObj
#IID_IHTMLEventObj$ = "{3050f32d-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLElement
#IID_IHTMLElement$ = "{3050f1ff-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLStyle
#IID_IHTMLStyle$ = "{3050f25e-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLFiltersCollection
#IID_IHTMLFiltersCollection$ = "{3050f3ee-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IElementBehaviorSite
#IID_IElementBehaviorSite$ = "{3050f427-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IElementBehavior
#IID_IElementBehavior$ = "{3050f425-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IElementBehaviorFactory
#IID_IElementBehaviorFactory$ = "{3050f429-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IElementBehaviorSiteOM
#IID_IElementBehaviorSiteOM$ = "{3050f489-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IElementBehaviorRender
#IID_IElementBehaviorRender$ = "{3050f4aa-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IElementBehaviorSiteRender
#IID_IElementBehaviorSiteRender$ = "{3050f4a7-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IDOMEvent
#IID_IDOMEvent$ = "{305104ba-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IEventTarget
#IID_IEventTarget$ = "{305104b9-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLDOMConstructor
#IID_IHTMLDOMConstructor$ = "{3051049b-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLStyleSheetRule
#IID_IHTMLStyleSheetRule$ = "{3050f357-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLRuleStyle
#IID_IHTMLRuleStyle$ = "{3050f3cf-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLCSSStyleDeclaration
#IID_IHTMLCSSStyleDeclaration$ = "{30510740-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLCSSStyleDeclaration2
#IID_IHTMLCSSStyleDeclaration2$ = "{305107d1-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLCSSStyleDeclaration3
#IID_IHTMLCSSStyleDeclaration3$ = "{3051085c-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLCSSStyleDeclaration4
#IID_IHTMLCSSStyleDeclaration4$ = "{d6100f3b-27c8-4132-afea-f0e4b1e00060}"

;- IID_IHTMLStyleEnabled
#IID_IHTMLStyleEnabled$ = "{305104c2-98b5-11cf-bb82-00aa00bdce0b}"

;- Class HTMLCSSStyleDeclaration
#CLSID_HTMLCSSStyleDeclaration$ = "{30510741-98b5-11cf-bb82-00aa00bdce0b}"
;- IID_IHTMLStyle2
#IID_IHTMLStyle2$ = "{3050f4a2-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLStyle3
#IID_IHTMLStyle3$ = "{3050f656-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLStyle4
#IID_IHTMLStyle4$ = "{3050f816-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLStyle5
#IID_IHTMLStyle5$ = "{3050f33a-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLStyle6
#IID_IHTMLStyle6$ = "{30510480-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLRuleStyle2
#IID_IHTMLRuleStyle2$ = "{3050f4ac-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLRuleStyle3
#IID_IHTMLRuleStyle3$ = "{3050f657-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLRuleStyle4
#IID_IHTMLRuleStyle4$ = "{3050f817-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLRuleStyle5
#IID_IHTMLRuleStyle5$ = "{3050f335-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLRuleStyle6
#IID_IHTMLRuleStyle6$ = "{30510471-98b5-11cf-bb82-00aa00bdce0b}"

;- Class HTMLStyle
#CLSID_HTMLStyle$ = "{3050f285-98b5-11cf-bb82-00aa00bdce0b}"
;- Class HTMLRuleStyle
#CLSID_HTMLRuleStyle$ = "{3050f3d0-98b5-11cf-bb82-00aa00bdce0b}"
;- IID_IHTMLStyleSheetRulesCollection
#IID_IHTMLStyleSheetRulesCollection$ = "{3050f2e5-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLStyleSheet
#IID_IHTMLStyleSheet$ = "{3050f2e3-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLStyleSheetsCollection
#IID_IHTMLStyleSheetsCollection$ = "{3050f37e-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLCSSRule
#IID_IHTMLCSSRule$ = "{305106e9-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLCSSImportRule
#IID_IHTMLCSSImportRule$ = "{305106ea-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLCSSMediaRule
#IID_IHTMLCSSMediaRule$ = "{305106eb-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLCSSMediaList
#IID_IHTMLCSSMediaList$ = "{30510731-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLCSSNamespaceRule
#IID_IHTMLCSSNamespaceRule$ = "{305106ee-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLMSCSSKeyframeRule
#IID_IHTMLMSCSSKeyframeRule$ = "{3051080c-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLMSCSSKeyframesRule
#IID_IHTMLMSCSSKeyframesRule$ = "{3051080d-98b5-11cf-bb82-00aa00bdce0b}"

;- Class HTMLCSSRule
#CLSID_HTMLCSSRule$ = "{305106ef-98b5-11cf-bb82-00aa00bdce0b}"
;- Class HTMLCSSImportRule
#CLSID_HTMLCSSImportRule$ = "{305106f0-98b5-11cf-bb82-00aa00bdce0b}"
;- Class HTMLCSSMediaRule
#CLSID_HTMLCSSMediaRule$ = "{305106f1-98b5-11cf-bb82-00aa00bdce0b}"
;- Class HTMLCSSMediaList
#CLSID_HTMLCSSMediaList$ = "{30510732-98b5-11cf-bb82-00aa00bdce0b}"
;- Class HTMLCSSNamespaceRule
#CLSID_HTMLCSSNamespaceRule$ = "{305106f2-98b5-11cf-bb82-00aa00bdce0b}"
;- Class HTMLMSCSSKeyframeRule
#CLSID_HTMLMSCSSKeyframeRule$ = "{3051080e-98b5-11cf-bb82-00aa00bdce0b}"
;- Class HTMLMSCSSKeyframesRule
#CLSID_HTMLMSCSSKeyframesRule$ = "{3051080f-98b5-11cf-bb82-00aa00bdce0b}"
;- IID_IHTMLRenderStyle
#IID_IHTMLRenderStyle$ = "{3050f6ae-98b5-11cf-bb82-00aa00bdce0b}"

;- Class HTMLRenderStyle
#CLSID_HTMLRenderStyle$ = "{3050f6aa-98b5-11cf-bb82-00aa00bdce0b}"
;- IID_IHTMLCurrentStyle
#IID_IHTMLCurrentStyle$ = "{3050f3db-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLCurrentStyle2
#IID_IHTMLCurrentStyle2$ = "{3050f658-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLCurrentStyle3
#IID_IHTMLCurrentStyle3$ = "{3050f818-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLCurrentStyle4
#IID_IHTMLCurrentStyle4$ = "{3050f33b-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLCurrentStyle5
#IID_IHTMLCurrentStyle5$ = "{30510481-98b5-11cf-bb82-00aa00bdce0b}"

;- Class HTMLCurrentStyle
#CLSID_HTMLCurrentStyle$ = "{3050f3dc-98b5-11cf-bb82-00aa00bdce0b}"
;- IID_IHTMLRect
#IID_IHTMLRect$ = "{3050f4a3-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLRect2
#IID_IHTMLRect2$ = "{3051076c-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLRectCollection
#IID_IHTMLRectCollection$ = "{3050f4a4-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLElementCollection
#IID_IHTMLElementCollection$ = "{3050f21f-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLElement2
#IID_IHTMLElement2$ = "{3050f434-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLAttributeCollection3
#IID_IHTMLAttributeCollection3$ = "{30510469-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLDOMAttribute
#IID_IHTMLDOMAttribute$ = "{3050f4b0-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IDOMDocumentType
#IID_IDOMDocumentType$ = "{30510738-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLDocument7
#IID_IHTMLDocument7$ = "{305104b8-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLWindow2
#IID_IHTMLWindow2$ = "{332c4427-26cb-11d0-b483-00c04fd90119}"

;- IID_IHTMLFramesCollection2
#IID_IHTMLFramesCollection2$ = "{332c4426-26cb-11d0-b483-00c04fd90119}"

;- IID_IHTMLImageElementFactory
#IID_IHTMLImageElementFactory$ = "{3050f38e-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLImgElement
#IID_IHTMLImgElement$ = "{3050f240-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLLocation
#IID_IHTMLLocation$ = "{163bb1e0-6e00-11cf-837a-48dc04c10000}"

;- IID_IOmHistory
#IID_IOmHistory$ = "{feceaaa2-8405-11cf-8ba1-00aa00476da6}"

;- IID_IOmNavigator
#IID_IOmNavigator$ = "{feceaaa5-8405-11cf-8ba1-00aa00476da6}"

;- IID_IHTMLMimeTypesCollection
#IID_IHTMLMimeTypesCollection$ = "{3050f3fc-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLPluginsCollection
#IID_IHTMLPluginsCollection$ = "{3050f3fd-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLOpsProfile
#IID_IHTMLOpsProfile$ = "{3050f401-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLDocument2
#IID_IHTMLDocument2$ = "{332c4425-26cb-11d0-b483-00c04fd90119}"

;- IID_IHTMLDocument
#IID_IHTMLDocument$ = "{626fc520-a41e-11cf-a731-00a0c9082637}"

;- IID_IHTMLSelectionObject
#IID_IHTMLSelectionObject$ = "{3050f25a-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLScreen
#IID_IHTMLScreen$ = "{3050f35c-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLOptionElementFactory
#IID_IHTMLOptionElementFactory$ = "{3050f38c-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLOptionElement
#IID_IHTMLOptionElement$ = "{3050f211-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLFormElement
#IID_IHTMLFormElement$ = "{3050f1f7-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLDOMNode
#IID_IHTMLDOMNode$ = "{3050f5da-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLSelection
#IID_IHTMLSelection$ = "{305104b6-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLDOMRange
#IID_IHTMLDOMRange$ = "{305104ae-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IDOMProcessingInstruction
#IID_IDOMProcessingInstruction$ = "{30510742-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLDOMNode3
#IID_IHTMLDOMNode3$ = "{305106e0-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLDOMNode2
#IID_IHTMLDOMNode2$ = "{3050f80b-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLDOMAttribute2
#IID_IHTMLDOMAttribute2$ = "{3050f810-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLDOMAttribute3
#IID_IHTMLDOMAttribute3$ = "{30510468-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLDOMAttribute4
#IID_IHTMLDOMAttribute4$ = "{305106f9-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLDOMTextNode
#IID_IHTMLDOMTextNode$ = "{3050f4b1-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLDOMTextNode2
#IID_IHTMLDOMTextNode2$ = "{3050f809-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLDOMTextNode3
#IID_IHTMLDOMTextNode3$ = "{3051073e-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLDOMImplementation
#IID_IHTMLDOMImplementation$ = "{3050f80d-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLDOMImplementation2
#IID_IHTMLDOMImplementation2$ = "{3051073c-98b5-11cf-bb82-00aa00bdce0b}"

;- Class HTMLDOMAttribute
#CLSID_HTMLDOMAttribute$ = "{3050f4b2-98b5-11cf-bb82-00aa00bdce0b}"
;- Class HTMLDOMTextNode
#CLSID_HTMLDOMTextNode$ = "{3050f4ba-98b5-11cf-bb82-00aa00bdce0b}"
;- Class HTMLDOMImplementation
#CLSID_HTMLDOMImplementation$ = "{3050f80e-98b5-11cf-bb82-00aa00bdce0b}"
;- IID_IHTMLAttributeCollection
#IID_IHTMLAttributeCollection$ = "{3050f4c3-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLAttributeCollection2
#IID_IHTMLAttributeCollection2$ = "{3050f80a-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLAttributeCollection4
#IID_IHTMLAttributeCollection4$ = "{305106fa-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLDOMChildrenCollection
#IID_IHTMLDOMChildrenCollection$ = "{3050f5ab-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLDOMChildrenCollection2
#IID_IHTMLDOMChildrenCollection2$ = "{30510791-98b5-11cf-bb82-00aa00bdce0b}"

;- Class HTMLAttributeCollection
#CLSID_HTMLAttributeCollection$ = "{3050f4cc-98b5-11cf-bb82-00aa00bdce0b}"
;- Class StaticNodeList
#CLSID_StaticNodeList$ = "{30510467-98b5-11cf-bb82-00aa00bdce0b}"
;- Class DOMChildrenCollection
#CLSID_DOMChildrenCollection$ = "{3050f5aa-98b5-11cf-bb82-00aa00bdce0b}"
;- IID_IRulesAppliedCollection
#IID_IRulesAppliedCollection$ = "{305104be-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IRulesApplied
#IID_IRulesApplied$ = "{305104bf-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLStyleSheetRulesAppliedCollection
#IID_IHTMLStyleSheetRulesAppliedCollection$ = "{305104c0-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLElement3
#IID_IHTMLElement3$ = "{3050f673-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLElement4
#IID_IHTMLElement4$ = "{3050f80f-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IElementSelector
#IID_IElementSelector$ = "{30510463-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLElementRender
#IID_IHTMLElementRender$ = "{3050f669-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLUniqueName
#IID_IHTMLUniqueName$ = "{3050f4d0-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLElement5
#IID_IHTMLElement5$ = "{3051045d-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLElement6
#IID_IHTMLElement6$ = "{305106f8-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLElement7
#IID_IHTMLElement7$ = "{305107aa-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLElementAppliedStyles
#IID_IHTMLElementAppliedStyles$ = "{305104bd-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IElementTraversal
#IID_IElementTraversal$ = "{30510736-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLDatabinding
#IID_IHTMLDatabinding$ = "{3050f3f2-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLElementDefaults
#IID_IHTMLElementDefaults$ = "{3050f6c9-98b5-11cf-bb82-00aa00bdce0b}"

;- Class HTMLDefaults
#CLSID_HTMLDefaults$ = "{3050f6c8-98b5-11cf-bb82-00aa00bdce0b}"
;- IID_IHTCDefaultDispatch
#IID_IHTCDefaultDispatch$ = "{3050f4fd-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTCPropertyBehavior
#IID_IHTCPropertyBehavior$ = "{3050f5df-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTCMethodBehavior
#IID_IHTCMethodBehavior$ = "{3050f631-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTCEventBehavior
#IID_IHTCEventBehavior$ = "{3050f4ff-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTCAttachBehavior
#IID_IHTCAttachBehavior$ = "{3050f5f4-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTCAttachBehavior2
#IID_IHTCAttachBehavior2$ = "{3050f7eb-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTCDescBehavior
#IID_IHTCDescBehavior$ = "{3050f5dc-98b5-11cf-bb82-00aa00bdce0b}"

;- Class HTCDefaultDispatch
#CLSID_HTCDefaultDispatch$ = "{3050f4fc-98b5-11cf-bb82-00aa00bdce0b}"
;- Class HTCPropertyBehavior
#CLSID_HTCPropertyBehavior$ = "{3050f5de-98b5-11cf-bb82-00aa00bdce0b}"
;- Class HTCMethodBehavior
#CLSID_HTCMethodBehavior$ = "{3050f630-98b5-11cf-bb82-00aa00bdce0b}"
;- Class HTCEventBehavior
#CLSID_HTCEventBehavior$ = "{3050f4fe-98b5-11cf-bb82-00aa00bdce0b}"
;- Class HTCAttachBehavior
#CLSID_HTCAttachBehavior$ = "{3050f5f5-98b5-11cf-bb82-00aa00bdce0b}"
;- Class HTCDescBehavior
#CLSID_HTCDescBehavior$ = "{3050f5dd-98b5-11cf-bb82-00aa00bdce0b}"
;- IID_IHTMLUrnCollection
#IID_IHTMLUrnCollection$ = "{3050f5e2-98b5-11cf-bb82-00aa00bdce0b}"

;- Class HTMLUrnCollection
#CLSID_HTMLUrnCollection$ = "{3050f580-98b5-11cf-bb82-00aa00bdce0b}"
;- IID_IHTMLGenericElement
#IID_IHTMLGenericElement$ = "{3050f4b7-98b5-11cf-bb82-00aa00bdce0b}"

;- Class HTMLGenericElement
#CLSID_HTMLGenericElement$ = "{3050f4b8-98b5-11cf-bb82-00aa00bdce0b}"
;- IID_IHTMLStyleSheetRuleApplied
#IID_IHTMLStyleSheetRuleApplied$ = "{305104c1-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLStyleSheetRule2
#IID_IHTMLStyleSheetRule2$ = "{305106fd-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLStyleSheetRulesCollection2
#IID_IHTMLStyleSheetRulesCollection2$ = "{305106e8-98b5-11cf-bb82-00aa00bdce0b}"

;- Class HTMLStyleSheetRule
#CLSID_HTMLStyleSheetRule$ = "{3050f3ce-98b5-11cf-bb82-00aa00bdce0b}"
;- Class HTMLStyleSheetRulesCollection
#CLSID_HTMLStyleSheetRulesCollection$ = "{3050f3cd-98b5-11cf-bb82-00aa00bdce0b}"
;- IID_IHTMLStyleSheetPage
#IID_IHTMLStyleSheetPage$ = "{3050f7ee-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLStyleSheetPage2
#IID_IHTMLStyleSheetPage2$ = "{305106ed-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLStyleSheetPagesCollection
#IID_IHTMLStyleSheetPagesCollection$ = "{3050f7f0-98b5-11cf-bb82-00aa00bdce0b}"

;- Class HTMLStyleSheetPage
#CLSID_HTMLStyleSheetPage$ = "{3050f7ef-98b5-11cf-bb82-00aa00bdce0b}"
;- Class HTMLStyleSheetPagesCollection
#CLSID_HTMLStyleSheetPagesCollection$ = "{3050f7f1-98b5-11cf-bb82-00aa00bdce0b}"
;- IID_IHTMLStyleSheet2
#IID_IHTMLStyleSheet2$ = "{3050f3d1-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLStyleSheet3
#IID_IHTMLStyleSheet3$ = "{30510496-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLStyleSheet4
#IID_IHTMLStyleSheet4$ = "{305106f4-98b5-11cf-bb82-00aa00bdce0b}"

;- Class HTMLStyleSheet
#CLSID_HTMLStyleSheet$ = "{3050f2e4-98b5-11cf-bb82-00aa00bdce0b}"
;- IID_IHTMLStyleSheetsCollection2
#IID_IHTMLStyleSheetsCollection2$ = "{305106e7-98b5-11cf-bb82-00aa00bdce0b}"

;- Class HTMLStyleSheetsCollection
#CLSID_HTMLStyleSheetsCollection$ = "{3050f37f-98b5-11cf-bb82-00aa00bdce0b}"
;- IID_IHTMLLinkElement
#IID_IHTMLLinkElement$ = "{3050f205-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLLinkElement2
#IID_IHTMLLinkElement2$ = "{3050f4e5-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLLinkElement3
#IID_IHTMLLinkElement3$ = "{3050f81e-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLLinkElement4
#IID_IHTMLLinkElement4$ = "{3051043a-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLLinkElement5
#IID_IHTMLLinkElement5$ = "{30510726-98b5-11cf-bb82-00aa00bdce0b}"

;- Class HTMLLinkElement
#CLSID_HTMLLinkElement$ = "{3050f277-98b5-11cf-bb82-00aa00bdce0b}"
;- IID_IHTMLTxtRange
#IID_IHTMLTxtRange$ = "{3050f220-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLTextRangeMetrics
#IID_IHTMLTextRangeMetrics$ = "{3050f40b-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLTextRangeMetrics2
#IID_IHTMLTextRangeMetrics2$ = "{3050f4a6-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLTxtRangeCollection
#IID_IHTMLTxtRangeCollection$ = "{3050f7ed-98b5-11cf-bb82-00aa00bdce0b}"

;- Class HTMLDOMRange
#CLSID_HTMLDOMRange$ = "{305106c3-98b5-11cf-bb82-00aa00bdce0b}"
;- IID_IHTMLFormElement2
#IID_IHTMLFormElement2$ = "{3050f4f6-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLFormElement3
#IID_IHTMLFormElement3$ = "{3050f836-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLSubmitData
#IID_IHTMLSubmitData$ = "{3050f645-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLFormElement4
#IID_IHTMLFormElement4$ = "{3051042c-98b5-11cf-bb82-00aa00bdce0b}"

;- Class HTMLFormElement
#CLSID_HTMLFormElement$ = "{3050f251-98b5-11cf-bb82-00aa00bdce0b}"
;- IID_IHTMLControlElement
#IID_IHTMLControlElement$ = "{3050f4e9-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLTextElement
#IID_IHTMLTextElement$ = "{3050f218-98b5-11cf-bb82-00aa00bdce0b}"

;- Class HTMLTextElement
#CLSID_HTMLTextElement$ = "{3050f26a-98b5-11cf-bb82-00aa00bdce0b}"
;- IID_IHTMLTextContainer
#IID_IHTMLTextContainer$ = "{3050f230-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLControlRange
#IID_IHTMLControlRange$ = "{3050f29c-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLControlRange2
#IID_IHTMLControlRange2$ = "{3050f65e-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLImgElement2
#IID_IHTMLImgElement2$ = "{3050f826-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLImgElement3
#IID_IHTMLImgElement3$ = "{30510434-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLImgElement4
#IID_IHTMLImgElement4$ = "{305107f6-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLMSImgElement
#IID_IHTMLMSImgElement$ = "{30510793-98b5-11cf-bb82-00aa00bdce0b}"

;- Class HTMLImg
#CLSID_HTMLImg$ = "{3050f241-98b5-11cf-bb82-00aa00bdce0b}"
;- Class HTMLImageElementFactory
#CLSID_HTMLImageElementFactory$ = "{3050f38f-98b5-11cf-bb82-00aa00bdce0b}"
;- IID_IHTMLBodyElement
#IID_IHTMLBodyElement$ = "{3050f1d8-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLBodyElement2
#IID_IHTMLBodyElement2$ = "{3050f5c5-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLBodyElement3
#IID_IHTMLBodyElement3$ = "{30510422-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLBodyElement4
#IID_IHTMLBodyElement4$ = "{30510795-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLBodyElement5
#IID_IHTMLBodyElement5$ = "{30510822-98b5-11cf-bb82-00aa00bdce0b}"

;- Class HTMLBody
#CLSID_HTMLBody$ = "{3050f24a-98b5-11cf-bb82-00aa00bdce0b}"
;- IID_IHTMLFontElement
#IID_IHTMLFontElement$ = "{3050f1d9-98b5-11cf-bb82-00aa00bdce0b}"

;- Class HTMLFontElement
#CLSID_HTMLFontElement$ = "{3050f27b-98b5-11cf-bb82-00aa00bdce0b}"
;- IID_IHTMLAnchorElement
#IID_IHTMLAnchorElement$ = "{3050f1da-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLAnchorElement2
#IID_IHTMLAnchorElement2$ = "{3050f825-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLAnchorElement3
#IID_IHTMLAnchorElement3$ = "{3051041d-98b5-11cf-bb82-00aa00bdce0b}"

;- Class HTMLAnchorElement
#CLSID_HTMLAnchorElement$ = "{3050f248-98b5-11cf-bb82-00aa00bdce0b}"
;- IID_IHTMLLabelElement
#IID_IHTMLLabelElement$ = "{3050f32a-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLLabelElement2
#IID_IHTMLLabelElement2$ = "{3050f832-98b5-11cf-bb82-00aa00bdce0b}"

;- Class HTMLLabelElement
#CLSID_HTMLLabelElement$ = "{3050f32b-98b5-11cf-bb82-00aa00bdce0b}"
;- IID_IHTMLListElement
#IID_IHTMLListElement$ = "{3050f20e-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLListElement2
#IID_IHTMLListElement2$ = "{3050f822-98b5-11cf-bb82-00aa00bdce0b}"

;- Class HTMLListElement
#CLSID_HTMLListElement$ = "{3050f272-98b5-11cf-bb82-00aa00bdce0b}"
;- IID_IHTMLUListElement
#IID_IHTMLUListElement$ = "{3050f1dd-98b5-11cf-bb82-00aa00bdce0b}"

;- Class HTMLUListElement
#CLSID_HTMLUListElement$ = "{3050f269-98b5-11cf-bb82-00aa00bdce0b}"
;- IID_IHTMLOListElement
#IID_IHTMLOListElement$ = "{3050f1de-98b5-11cf-bb82-00aa00bdce0b}"

;- Class HTMLOListElement
#CLSID_HTMLOListElement$ = "{3050f270-98b5-11cf-bb82-00aa00bdce0b}"
;- IID_IHTMLLIElement
#IID_IHTMLLIElement$ = "{3050f1e0-98b5-11cf-bb82-00aa00bdce0b}"

;- Class HTMLLIElement
#CLSID_HTMLLIElement$ = "{3050f273-98b5-11cf-bb82-00aa00bdce0b}"
;- IID_IHTMLBlockElement
#IID_IHTMLBlockElement$ = "{3050f208-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLBlockElement2
#IID_IHTMLBlockElement2$ = "{3050f823-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLBlockElement3
#IID_IHTMLBlockElement3$ = "{30510494-98b5-11cf-bb82-00aa00bdce0b}"

;- Class HTMLBlockElement
#CLSID_HTMLBlockElement$ = "{3050f281-98b5-11cf-bb82-00aa00bdce0b}"
;- IID_IHTMLDivElement
#IID_IHTMLDivElement$ = "{3050f200-98b5-11cf-bb82-00aa00bdce0b}"

;- Class HTMLDivElement
#CLSID_HTMLDivElement$ = "{3050f27e-98b5-11cf-bb82-00aa00bdce0b}"
;- IID_IHTMLDDElement
#IID_IHTMLDDElement$ = "{3050f1f2-98b5-11cf-bb82-00aa00bdce0b}"

;- Class HTMLDDElement
#CLSID_HTMLDDElement$ = "{3050f27f-98b5-11cf-bb82-00aa00bdce0b}"
;- IID_IHTMLDTElement
#IID_IHTMLDTElement$ = "{3050f1f3-98b5-11cf-bb82-00aa00bdce0b}"

;- Class HTMLDTElement
#CLSID_HTMLDTElement$ = "{3050f27c-98b5-11cf-bb82-00aa00bdce0b}"
;- IID_IHTMLBRElement
#IID_IHTMLBRElement$ = "{3050f1f0-98b5-11cf-bb82-00aa00bdce0b}"

;- Class HTMLBRElement
#CLSID_HTMLBRElement$ = "{3050f280-98b5-11cf-bb82-00aa00bdce0b}"
;- IID_IHTMLDListElement
#IID_IHTMLDListElement$ = "{3050f1f1-98b5-11cf-bb82-00aa00bdce0b}"

;- Class HTMLDListElement
#CLSID_HTMLDListElement$ = "{3050f27d-98b5-11cf-bb82-00aa00bdce0b}"
;- IID_IHTMLHRElement
#IID_IHTMLHRElement$ = "{3050f1f4-98b5-11cf-bb82-00aa00bdce0b}"

;- Class HTMLHRElement
#CLSID_HTMLHRElement$ = "{3050f252-98b5-11cf-bb82-00aa00bdce0b}"
;- IID_IHTMLParaElement
#IID_IHTMLParaElement$ = "{3050f1f5-98b5-11cf-bb82-00aa00bdce0b}"

;- Class HTMLParaElement
#CLSID_HTMLParaElement$ = "{3050f26f-98b5-11cf-bb82-00aa00bdce0b}"
;- IID_IHTMLElementCollection2
#IID_IHTMLElementCollection2$ = "{3050f5ee-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLElementCollection3
#IID_IHTMLElementCollection3$ = "{3050f835-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLElementCollection4
#IID_IHTMLElementCollection4$ = "{30510425-98b5-11cf-bb82-00aa00bdce0b}"

;- Class HTMLElementCollection
#CLSID_HTMLElementCollection$ = "{3050f4cb-98b5-11cf-bb82-00aa00bdce0b}"
;- IID_IHTMLHeaderElement
#IID_IHTMLHeaderElement$ = "{3050f1f6-98b5-11cf-bb82-00aa00bdce0b}"

;- Class HTMLHeaderElement
#CLSID_HTMLHeaderElement$ = "{3050f27a-98b5-11cf-bb82-00aa00bdce0b}"
;- IID_IHTMLSelectElementEx
#IID_IHTMLSelectElementEx$ = "{3050f2d1-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLSelectElement
#IID_IHTMLSelectElement$ = "{3050f244-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLSelectElement2
#IID_IHTMLSelectElement2$ = "{3050f5ed-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLSelectElement4
#IID_IHTMLSelectElement4$ = "{3050f838-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLSelectElement5
#IID_IHTMLSelectElement5$ = "{3051049d-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLSelectElement6
#IID_IHTMLSelectElement6$ = "{30510760-98b6-11cf-bb82-00aa00bdce0b}"

;- Class HTMLSelectElement
#CLSID_HTMLSelectElement$ = "{3050f245-98b5-11cf-bb82-00aa00bdce0b}"
;- Class HTMLWndSelectElement
#CLSID_HTMLWndSelectElement$ = "{3050f2cf-98b5-11cf-bb82-00aa00bdce0b}"
;- IID_IHTMLSelectionObject2
#IID_IHTMLSelectionObject2$ = "{3050f7ec-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLOptionElement3
#IID_IHTMLOptionElement3$ = "{3050f820-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLOptionElement4
#IID_IHTMLOptionElement4$ = "{305107b4-98b5-11cf-bb82-00aa00bdce0b}"

;- Class HTMLOptionElement
#CLSID_HTMLOptionElement$ = "{3050f24d-98b5-11cf-bb82-00aa00bdce0b}"
;- Class HTMLOptionElementFactory
#CLSID_HTMLOptionElementFactory$ = "{3050f38d-98b5-11cf-bb82-00aa00bdce0b}"
;- Class HTMLWndOptionElement
#CLSID_HTMLWndOptionElement$ = "{3050f2d0-98b5-11cf-bb82-00aa00bdce0b}"
;- IID_IHTMLInputElement
#IID_IHTMLInputElement$ = "{3050f5d2-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLInputElement2
#IID_IHTMLInputElement2$ = "{3050f821-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLInputElement3
#IID_IHTMLInputElement3$ = "{30510435-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLInputButtonElement
#IID_IHTMLInputButtonElement$ = "{3050f2b2-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLInputHiddenElement
#IID_IHTMLInputHiddenElement$ = "{3050f2a4-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLInputTextElement
#IID_IHTMLInputTextElement$ = "{3050f2a6-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLInputTextElement2
#IID_IHTMLInputTextElement2$ = "{3050f2d2-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLInputFileElement
#IID_IHTMLInputFileElement$ = "{3050f2ad-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLOptionButtonElement
#IID_IHTMLOptionButtonElement$ = "{3050f2bc-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLInputImage
#IID_IHTMLInputImage$ = "{3050f2c2-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLInputRangeElement
#IID_IHTMLInputRangeElement$ = "{3050f2d4-98b5-11cf-bb82-00aa00bdce0b}"

;- Class HTMLInputElement
#CLSID_HTMLInputElement$ = "{3050f5d8-98b5-11cf-bb82-00aa00bdce0b}"
;- IID_IHTMLTextAreaElement
#IID_IHTMLTextAreaElement$ = "{3050f2aa-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLTextAreaElement2
#IID_IHTMLTextAreaElement2$ = "{3050f2d3-98b5-11cf-bb82-00aa00bdce0b}"

;- Class HTMLTextAreaElement
#CLSID_HTMLTextAreaElement$ = "{3050f2ac-98b5-11cf-bb82-00aa00bdce0b}"
;- Class HTMLRichtextElement
#CLSID_HTMLRichtextElement$ = "{3050f2df-98b5-11cf-bb82-00aa00bdce0b}"
;- IID_IHTMLButtonElement
#IID_IHTMLButtonElement$ = "{3050f2bb-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLButtonElement2
#IID_IHTMLButtonElement2$ = "{305106f3-98b5-11cf-bb82-00aa00bdce0b}"

;- Class HTMLButtonElement
#CLSID_HTMLButtonElement$ = "{3050f2c6-98b5-11cf-bb82-00aa00bdce0b}"
;- IID_IHTMLMarqueeElement
#IID_IHTMLMarqueeElement$ = "{3050f2b5-98b5-11cf-bb82-00aa00bdce0b}"

;- Class HTMLMarqueeElement
#CLSID_HTMLMarqueeElement$ = "{3050f2b9-98b5-11cf-bb82-00aa00bdce0b}"
;- IID_IHTMLHtmlElement
#IID_IHTMLHtmlElement$ = "{3050f81c-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLHeadElement
#IID_IHTMLHeadElement$ = "{3050f81d-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLHeadElement2
#IID_IHTMLHeadElement2$ = "{3051042f-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLTitleElement
#IID_IHTMLTitleElement$ = "{3050f322-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLMetaElement
#IID_IHTMLMetaElement$ = "{3050f203-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLMetaElement2
#IID_IHTMLMetaElement2$ = "{3050f81f-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLMetaElement3
#IID_IHTMLMetaElement3$ = "{30510495-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLBaseElement
#IID_IHTMLBaseElement$ = "{3050f204-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLBaseElement2
#IID_IHTMLBaseElement2$ = "{30510420-98b5-11cf-bb82-00aa00bdce0b}"

;- Class HTMLHtmlElement
#CLSID_HTMLHtmlElement$ = "{3050f491-98b5-11cf-bb82-00aa00bdce0b}"
;- Class HTMLHeadElement
#CLSID_HTMLHeadElement$ = "{3050f493-98b5-11cf-bb82-00aa00bdce0b}"
;- Class HTMLTitleElement
#CLSID_HTMLTitleElement$ = "{3050f284-98b5-11cf-bb82-00aa00bdce0b}"
;- Class HTMLMetaElement
#CLSID_HTMLMetaElement$ = "{3050f275-98b5-11cf-bb82-00aa00bdce0b}"
;- Class HTMLBaseElement
#CLSID_HTMLBaseElement$ = "{3050f276-98b5-11cf-bb82-00aa00bdce0b}"
;- IID_IHTMLIsIndexElement
#IID_IHTMLIsIndexElement$ = "{3050f206-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLIsIndexElement2
#IID_IHTMLIsIndexElement2$ = "{3050f82f-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLNextIdElement
#IID_IHTMLNextIdElement$ = "{3050f207-98b5-11cf-bb82-00aa00bdce0b}"

;- Class HTMLIsIndexElement
#CLSID_HTMLIsIndexElement$ = "{3050f278-98b5-11cf-bb82-00aa00bdce0b}"
;- Class HTMLNextIdElement
#CLSID_HTMLNextIdElement$ = "{3050f279-98b5-11cf-bb82-00aa00bdce0b}"
;- IID_IHTMLBaseFontElement
#IID_IHTMLBaseFontElement$ = "{3050f202-98b5-11cf-bb82-00aa00bdce0b}"

;- Class HTMLBaseFontElement
#CLSID_HTMLBaseFontElement$ = "{3050f282-98b5-11cf-bb82-00aa00bdce0b}"
;- IID_IHTMLUnknownElement
#IID_IHTMLUnknownElement$ = "{3050f209-98b5-11cf-bb82-00aa00bdce0b}"

;- Class HTMLUnknownElement
#CLSID_HTMLUnknownElement$ = "{3050f268-98b5-11cf-bb82-00aa00bdce0b}"
;- IID_IWebGeolocation
#IID_IWebGeolocation$ = "{305107c5-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_INavigatorGeolocation
#IID_INavigatorGeolocation$ = "{305107cf-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_INavigatorDoNotTrack
#IID_INavigatorDoNotTrack$ = "{30510804-98b5-11cf-bb82-00aa00bdce0b}"

;- Class HTMLHistory
#CLSID_HTMLHistory$ = "{feceaaa3-8405-11cf-8ba1-00aa00476da6}"
;- Class COpsProfile
#CLSID_COpsProfile$ = "{3050f402-98b5-11cf-bb82-00aa00bdce0b}"
;- Class HTMLNavigator
#CLSID_HTMLNavigator$ = "{feceaaa6-8405-11cf-8ba1-00aa00476da6}"
;- Class HTMLLocation
#CLSID_HTMLLocation$ = "{163bb1e1-6e00-11cf-837a-48dc04c10000}"
;- Class CMimeTypes
#CLSID_CMimeTypes$ = "{3050f3fe-98b5-11cf-bb82-00aa00bdce0b}"
;- Class CPlugins
#CLSID_CPlugins$ = "{3050f3ff-98b5-11cf-bb82-00aa00bdce0b}"
;- IID_IHTMLBookmarkCollection
#IID_IHTMLBookmarkCollection$ = "{3050f4ce-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLDataTransfer
#IID_IHTMLDataTransfer$ = "{3050f4b3-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLEventObj2
#IID_IHTMLEventObj2$ = "{3050f48b-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLEventObj3
#IID_IHTMLEventObj3$ = "{3050f680-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLEventObj4
#IID_IHTMLEventObj4$ = "{3050f814-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLEventObj5
#IID_IHTMLEventObj5$ = "{30510478-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLEventObj6
#IID_IHTMLEventObj6$ = "{30510734-98b5-11cf-bb82-00aa00bdce0b}"

;- Class CEventObj
#CLSID_CEventObj$ = "{3050f48a-98b5-11cf-bb82-00aa00bdce0b}"
;- IID_IHTMLStyleMedia
#IID_IHTMLStyleMedia$ = "{3051074b-98b5-11cf-bb82-00aa00bdce0b}"

;- Class HTMLStyleMedia
#CLSID_HTMLStyleMedia$ = "{3051074c-98b5-11cf-bb82-00aa00bdce0b}"
;- Class FramesCollection
#CLSID_FramesCollection$ = "{3050f7f6-98b5-11cf-bb82-00aa00bdce0b}"
;- IID_IHTMLWindow3
#IID_IHTMLWindow3$ = "{3050f4ae-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLFrameBase
#IID_IHTMLFrameBase$ = "{3050f311-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLStorage
#IID_IHTMLStorage$ = "{30510474-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLPerformance
#IID_IHTMLPerformance$ = "{3051074e-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLPerformanceNavigation
#IID_IHTMLPerformanceNavigation$ = "{30510750-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLPerformanceTiming
#IID_IHTMLPerformanceTiming$ = "{30510752-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLApplicationCache
#IID_IHTMLApplicationCache$ = "{30510828-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLScreen2
#IID_IHTMLScreen2$ = "{3050f84a-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLScreen3
#IID_IHTMLScreen3$ = "{305104a1-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLScreen4
#IID_IHTMLScreen4$ = "{3051076b-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLWindow4
#IID_IHTMLWindow4$ = "{3050f6cf-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLWindow5
#IID_IHTMLWindow5$ = "{3051040e-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLWindow6
#IID_IHTMLWindow6$ = "{30510453-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLWindow7
#IID_IHTMLWindow7$ = "{305104b7-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLWindow8
#IID_IHTMLWindow8$ = "{305107ab-98b5-11cf-bb82-00aa00bdce0b}"

;- Class HTMLScreen
#CLSID_HTMLScreen$ = "{3050f35d-98b5-11cf-bb82-00aa00bdce0b}"
;- Class HTMLWindow2
#CLSID_HTMLWindow2$ = "{d48a6ec6-6a4a-11cf-94a7-444553540000}"
;- Class HTMLWindowProxy
#CLSID_HTMLWindowProxy$ = "{3050f391-98b5-11cf-bb82-00aa00bdce0b}"
;- IID_IHTMLDocumentCompatibleInfo
#IID_IHTMLDocumentCompatibleInfo$ = "{3051041a-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLDocumentCompatibleInfoCollection
#IID_IHTMLDocumentCompatibleInfoCollection$ = "{30510418-98b5-11cf-bb82-00aa00bdce0b}"

;- Class HTMLDocumentCompatibleInfo
#CLSID_HTMLDocumentCompatibleInfo$ = "{3051041b-98b5-11cf-bb82-00aa00bdce0b}"
;- Class HTMLDocumentCompatibleInfoCollection
#CLSID_HTMLDocumentCompatibleInfoCollection$ = "{30510419-98b5-11cf-bb82-00aa00bdce0b}"
;- IID_ISVGSVGElement
#IID_ISVGSVGElement$ = "{305104e7-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_ISVGAnimatedLength
#IID_ISVGAnimatedLength$ = "{305104d0-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_ISVGLength
#IID_ISVGLength$ = "{305104cf-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_ISVGRect
#IID_ISVGRect$ = "{305104d7-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_ISVGViewSpec
#IID_ISVGViewSpec$ = "{305104e2-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_ISVGPoint
#IID_ISVGPoint$ = "{305104f4-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_ISVGMatrix
#IID_ISVGMatrix$ = "{305104f6-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_ISVGElement
#IID_ISVGElement$ = "{305104c5-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_ISVGAnimatedEnumeration
#IID_ISVGAnimatedEnumeration$ = "{305104c9-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_ISVGNumber
#IID_ISVGNumber$ = "{305104cb-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_ISVGAngle
#IID_ISVGAngle$ = "{305104d3-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_ISVGTransform
#IID_ISVGTransform$ = "{305104f7-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IDOMNodeIterator
#IID_IDOMNodeIterator$ = "{30510746-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IDOMTreeWalker
#IID_IDOMTreeWalker$ = "{30510748-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLDocument3
#IID_IHTMLDocument3$ = "{3050f485-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLDocument4
#IID_IHTMLDocument4$ = "{3050f69a-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLDocument5
#IID_IHTMLDocument5$ = "{3050f80c-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLDocument6
#IID_IHTMLDocument6$ = "{30510417-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLDocument8
#IID_IHTMLDocument8$ = "{305107d0-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IDocumentEvent
#IID_IDocumentEvent$ = "{305104bc-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IDocumentRange
#IID_IDocumentRange$ = "{305104af-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IDocumentSelector
#IID_IDocumentSelector$ = "{30510462-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IDocumentTraversal
#IID_IDocumentTraversal$ = "{30510744-98b5-11cf-bb82-00aa00bdce0b}"

;- Class HTMLDocument
#CLSID_HTMLDocument$ = "{25336920-03f9-11cf-8fd0-00aa00686f13}"
;- IID_ISVGDocument
#IID_ISVGDocument$ = "{305104e6-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IWebBridge
#IID_IWebBridge$ = "{ae24fdad-03c6-11d1-8b76-0080c744f389}"

;- IID_IWBScriptControl
#IID_IWBScriptControl$ = "{a5170870-0cf8-11d1-8b91-0080c744f389}"

;- Class Scriptlet
#CLSID_Scriptlet$ = "{ae24fdae-03c6-11d1-8b76-0080c744f389}"
;- IID_IHTMLEmbedElement
#IID_IHTMLEmbedElement$ = "{3050f25f-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLEmbedElement2
#IID_IHTMLEmbedElement2$ = "{30510493-98b5-11cf-bb82-00aa00bdce0b}"

;- Class HTMLEmbed
#CLSID_HTMLEmbed$ = "{3050f25d-98b5-11cf-bb82-00aa00bdce0b}"
;- IID_IGetSVGDocument
#IID_IGetSVGDocument$ = "{305105ab-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLAreasCollection
#IID_IHTMLAreasCollection$ = "{3050f383-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLAreasCollection2
#IID_IHTMLAreasCollection2$ = "{3050f5ec-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLAreasCollection3
#IID_IHTMLAreasCollection3$ = "{3050f837-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLAreasCollection4
#IID_IHTMLAreasCollection4$ = "{30510492-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLMapElement
#IID_IHTMLMapElement$ = "{3050f266-98b5-11cf-bb82-00aa00bdce0b}"

;- Class HTMLAreasCollection
#CLSID_HTMLAreasCollection$ = "{3050f4ca-98b5-11cf-bb82-00aa00bdce0b}"
;- Class HTMLMapElement
#CLSID_HTMLMapElement$ = "{3050f271-98b5-11cf-bb82-00aa00bdce0b}"
;- IID_IHTMLAreaElement
#IID_IHTMLAreaElement$ = "{3050f265-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLAreaElement2
#IID_IHTMLAreaElement2$ = "{3051041f-98b5-11cf-bb82-00aa00bdce0b}"

;- Class HTMLAreaElement
#CLSID_HTMLAreaElement$ = "{3050f283-98b5-11cf-bb82-00aa00bdce0b}"
;- IID_IHTMLTableCaption
#IID_IHTMLTableCaption$ = "{3050f2eb-98b5-11cf-bb82-00aa00bdce0b}"

;- Class HTMLTableCaption
#CLSID_HTMLTableCaption$ = "{3050f2ec-98b5-11cf-bb82-00aa00bdce0b}"
;- IID_IHTMLCommentElement
#IID_IHTMLCommentElement$ = "{3050f20c-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLCommentElement2
#IID_IHTMLCommentElement2$ = "{3050f813-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLCommentElement3
#IID_IHTMLCommentElement3$ = "{3051073f-98b5-11cf-bb82-00aa00bdce0b}"

;- Class HTMLCommentElement
#CLSID_HTMLCommentElement$ = "{3050f317-98b5-11cf-bb82-00aa00bdce0b}"
;- IID_IHTMLPhraseElement
#IID_IHTMLPhraseElement$ = "{3050f20a-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLPhraseElement2
#IID_IHTMLPhraseElement2$ = "{3050f824-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLPhraseElement3
#IID_IHTMLPhraseElement3$ = "{3051043d-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLSpanElement
#IID_IHTMLSpanElement$ = "{3050f3f3-98b5-11cf-bb82-00aa00bdce0b}"

;- Class HTMLPhraseElement
#CLSID_HTMLPhraseElement$ = "{3050f26e-98b5-11cf-bb82-00aa00bdce0b}"
;- Class HTMLSpanElement
#CLSID_HTMLSpanElement$ = "{3050f3f5-98b4-11cf-bb82-00aa00bdce0b}"
;- IID_IHTMLTableSection
#IID_IHTMLTableSection$ = "{3050f23b-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLTable
#IID_IHTMLTable$ = "{3050f21e-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLTable2
#IID_IHTMLTable2$ = "{3050f4ad-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLTable3
#IID_IHTMLTable3$ = "{3050f829-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLTable4
#IID_IHTMLTable4$ = "{305106c2-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLTableCol
#IID_IHTMLTableCol$ = "{3050f23a-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLTableCol2
#IID_IHTMLTableCol2$ = "{3050f82a-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLTableCol3
#IID_IHTMLTableCol3$ = "{305106c4-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLTableSection2
#IID_IHTMLTableSection2$ = "{3050f5c7-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLTableSection3
#IID_IHTMLTableSection3$ = "{3050f82b-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLTableSection4
#IID_IHTMLTableSection4$ = "{305106c5-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLTableRow
#IID_IHTMLTableRow$ = "{3050f23c-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLTableRow2
#IID_IHTMLTableRow2$ = "{3050f4a1-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLTableRow3
#IID_IHTMLTableRow3$ = "{3050f82c-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLTableRow4
#IID_IHTMLTableRow4$ = "{305106c6-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLTableRowMetrics
#IID_IHTMLTableRowMetrics$ = "{3050f413-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLTableCell
#IID_IHTMLTableCell$ = "{3050f23d-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLTableCell2
#IID_IHTMLTableCell2$ = "{3050f82d-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLTableCell3
#IID_IHTMLTableCell3$ = "{305106c7-98b5-11cf-bb82-00aa00bdce0b}"

;- Class HTMLTable
#CLSID_HTMLTable$ = "{3050f26b-98b5-11cf-bb82-00aa00bdce0b}"
;- Class HTMLTableCol
#CLSID_HTMLTableCol$ = "{3050f26c-98b5-11cf-bb82-00aa00bdce0b}"
;- Class HTMLTableSection
#CLSID_HTMLTableSection$ = "{3050f2e9-98b5-11cf-bb82-00aa00bdce0b}"
;- Class HTMLTableRow
#CLSID_HTMLTableRow$ = "{3050f26d-98b5-11cf-bb82-00aa00bdce0b}"
;- Class HTMLTableCell
#CLSID_HTMLTableCell$ = "{3050f246-98b5-11cf-bb82-00aa00bdce0b}"
;- IID_IHTMLScriptElement
#IID_IHTMLScriptElement$ = "{3050f28b-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLScriptElement2
#IID_IHTMLScriptElement2$ = "{3050f828-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLScriptElement3
#IID_IHTMLScriptElement3$ = "{30510447-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLScriptElement4
#IID_IHTMLScriptElement4$ = "{30510801-98b5-11cf-bb82-00aa00bdce0b}"

;- Class HTMLScriptElement
#CLSID_HTMLScriptElement$ = "{3050f28c-98b5-11cf-bb82-00aa00bdce0b}"
;- IID_IHTMLNoShowElement
#IID_IHTMLNoShowElement$ = "{3050f38a-98b5-11cf-bb82-00aa00bdce0b}"

;- Class HTMLNoShowElement
#CLSID_HTMLNoShowElement$ = "{3050f38b-98b5-11cf-bb82-00aa00bdce0b}"
;- IID_IHTMLObjectElement
#IID_IHTMLObjectElement$ = "{3050f24f-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLObjectElement2
#IID_IHTMLObjectElement2$ = "{3050f4cd-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLObjectElement3
#IID_IHTMLObjectElement3$ = "{3050f827-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLObjectElement4
#IID_IHTMLObjectElement4$ = "{3051043e-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLObjectElement5
#IID_IHTMLObjectElement5$ = "{305104b5-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLParamElement
#IID_IHTMLParamElement$ = "{3050f83d-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLParamElement2
#IID_IHTMLParamElement2$ = "{30510444-98b5-11cf-bb82-00aa00bdce0b}"

;- Class HTMLObjectElement
#CLSID_HTMLObjectElement$ = "{3050f24e-98b5-11cf-bb82-00aa00bdce0b}"
;- Class HTMLParamElement
#CLSID_HTMLParamElement$ = "{3050f83e-98b5-11cf-bb82-00aa00bdce0b}"
;- IID_IHTMLFrameBase2
#IID_IHTMLFrameBase2$ = "{3050f6db-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLFrameBase3
#IID_IHTMLFrameBase3$ = "{3050f82e-98b5-11cf-bb82-00aa00bdce0b}"

;- Class HTMLFrameBase
#CLSID_HTMLFrameBase$ = "{3050f312-98b5-11cf-bb82-00aa00bdce0b}"
;- IID_IHTMLFrameElement
#IID_IHTMLFrameElement$ = "{3050f313-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLFrameElement2
#IID_IHTMLFrameElement2$ = "{3050f7f5-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLFrameElement3
#IID_IHTMLFrameElement3$ = "{3051042d-98b5-11cf-bb82-00aa00bdce0b}"

;- Class HTMLFrameElement
#CLSID_HTMLFrameElement$ = "{3050f314-98b5-11cf-bb82-00aa00bdce0b}"
;- IID_IHTMLIFrameElement
#IID_IHTMLIFrameElement$ = "{3050f315-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLIFrameElement2
#IID_IHTMLIFrameElement2$ = "{3050f4e6-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLIFrameElement3
#IID_IHTMLIFrameElement3$ = "{30510433-98b5-11cf-bb82-00aa00bdce0b}"

;- Class HTMLIFrame
#CLSID_HTMLIFrame$ = "{3050f316-98b5-11cf-bb82-00aa00bdce0b}"
;- IID_IHTMLDivPosition
#IID_IHTMLDivPosition$ = "{3050f212-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLFieldSetElement
#IID_IHTMLFieldSetElement$ = "{3050f3e7-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLFieldSetElement2
#IID_IHTMLFieldSetElement2$ = "{3050f833-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLLegendElement
#IID_IHTMLLegendElement$ = "{3050f3ea-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLLegendElement2
#IID_IHTMLLegendElement2$ = "{3050f834-98b5-11cf-bb82-00aa00bdce0b}"

;- Class HTMLDivPosition
#CLSID_HTMLDivPosition$ = "{3050f249-98b5-11cf-bb82-00aa00bdce0b}"
;- Class HTMLFieldSetElement
#CLSID_HTMLFieldSetElement$ = "{3050f3e8-98b5-11cf-bb82-00aa00bdce0b}"
;- Class HTMLLegendElement
#CLSID_HTMLLegendElement$ = "{3050f3e9-98b5-11cf-bb82-00aa00bdce0b}"
;- IID_IHTMLSpanFlow
#IID_IHTMLSpanFlow$ = "{3050f3e5-98b5-11cf-bb82-00aa00bdce0b}"

;- Class HTMLSpanFlow
#CLSID_HTMLSpanFlow$ = "{3050f3e6-98b5-11cf-bb82-00aa00bdce0b}"
;- IID_IHTMLFrameSetElement
#IID_IHTMLFrameSetElement$ = "{3050f319-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLFrameSetElement2
#IID_IHTMLFrameSetElement2$ = "{3050f5c6-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLFrameSetElement3
#IID_IHTMLFrameSetElement3$ = "{30510796-98b5-11cf-bb82-00aa00bdce0b}"

;- Class HTMLFrameSetSite
#CLSID_HTMLFrameSetSite$ = "{3050f31a-98b5-11cf-bb82-00aa00bdce0b}"
;- IID_IHTMLBGsound
#IID_IHTMLBGsound$ = "{3050f369-98b5-11cf-bb82-00aa00bdce0b}"

;- Class HTMLBGsound
#CLSID_HTMLBGsound$ = "{3050f370-98b5-11cf-bb82-00aa00bdce0b}"
;- IID_IHTMLFontNamesCollection
#IID_IHTMLFontNamesCollection$ = "{3050f376-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLFontSizesCollection
#IID_IHTMLFontSizesCollection$ = "{3050f377-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLOptionsHolder
#IID_IHTMLOptionsHolder$ = "{3050f378-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLStyleElement
#IID_IHTMLStyleElement$ = "{3050f375-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLStyleElement2
#IID_IHTMLStyleElement2$ = "{3051072a-98b5-11cf-bb82-00aa00bdce0b}"

;- Class HTMLStyleElement
#CLSID_HTMLStyleElement$ = "{3050f37d-98b5-11cf-bb82-00aa00bdce0b}"
;- IID_IHTMLStyleFontFace
#IID_IHTMLStyleFontFace$ = "{3050f3d5-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLStyleFontFace2
#IID_IHTMLStyleFontFace2$ = "{305106ec-98b5-11cf-bb82-00aa00bdce0b}"

;- Class HTMLStyleFontFace
#CLSID_HTMLStyleFontFace$ = "{3050f3d4-98b5-11cf-bb82-00aa00bdce0b}"
;- IID_IHTMLXDomainRequest
#IID_IHTMLXDomainRequest$ = "{30510454-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLXDomainRequestFactory
#IID_IHTMLXDomainRequestFactory$ = "{30510456-98b5-11cf-bb82-00aa00bdce0b}"

;- Class XDomainRequest
#CLSID_XDomainRequest$ = "{30510455-98b5-11cf-bb82-00aa00bdce0b}"
;- Class XDomainRequestFactory
#CLSID_XDomainRequestFactory$ = "{30510457-98b5-11cf-bb82-00aa00bdce0b}"
;- IID_IHTMLStorage2
#IID_IHTMLStorage2$ = "{30510799-98b5-11cf-bb82-00aa00bdce0b}"

;- Class HTMLStorage
#CLSID_HTMLStorage$ = "{30510475-98b5-11cf-bb82-00aa00bdce0b}"
;- Class DOMEvent
#CLSID_DOMEvent$ = "{305104bb-98b5-11cf-bb82-00aa00bdce0b}"
;- IID_IDOMUIEvent
#IID_IDOMUIEvent$ = "{305106ca-98b5-11cf-bb82-00aa00bdce0b}"

;- Class DOMUIEvent
#CLSID_DOMUIEvent$ = "{305106cb-98b5-11cf-bb82-00aa00bdce0b}"
;- IID_IDOMMouseEvent
#IID_IDOMMouseEvent$ = "{305106ce-98b5-11cf-bb82-00aa00bdce0b}"

;- Class DOMMouseEvent
#CLSID_DOMMouseEvent$ = "{305106cf-98b5-11cf-bb82-00aa00bdce0b}"
;- IID_IDOMDragEvent
#IID_IDOMDragEvent$ = "{30510761-98b5-11cf-bb82-00aa00bdce0b}"

;- Class DOMDragEvent
#CLSID_DOMDragEvent$ = "{30510762-98b5-11cf-bb82-00aa00bdce0b}"
;- IID_IDOMMouseWheelEvent
#IID_IDOMMouseWheelEvent$ = "{305106d0-98b5-11cf-bb82-00aa00bdce0b}"

;- Class DOMMouseWheelEvent
#CLSID_DOMMouseWheelEvent$ = "{305106d1-98b5-11cf-bb82-00aa00bdce0b}"
;- IID_IDOMWheelEvent
#IID_IDOMWheelEvent$ = "{305106d2-98b5-11cf-bb82-00aa00bdce0b}"

;- Class DOMWheelEvent
#CLSID_DOMWheelEvent$ = "{305106d3-98b5-11cf-bb82-00aa00bdce0b}"
;- IID_IDOMTextEvent
#IID_IDOMTextEvent$ = "{305106d4-98b5-11cf-bb82-00aa00bdce0b}"

;- Class DOMTextEvent
#CLSID_DOMTextEvent$ = "{305106d5-98b5-11cf-bb82-00aa00bdce0b}"
;- IID_IDOMKeyboardEvent
#IID_IDOMKeyboardEvent$ = "{305106d6-98b5-11cf-bb82-00aa00bdce0b}"

;- Class DOMKeyboardEvent
#CLSID_DOMKeyboardEvent$ = "{305106d7-98b5-11cf-bb82-00aa00bdce0b}"
;- IID_IDOMCompositionEvent
#IID_IDOMCompositionEvent$ = "{305106d8-98b5-11cf-bb82-00aa00bdce0b}"

;- Class DOMCompositionEvent
#CLSID_DOMCompositionEvent$ = "{305106d9-98b5-11cf-bb82-00aa00bdce0b}"
;- IID_IDOMMutationEvent
#IID_IDOMMutationEvent$ = "{305106da-98b5-11cf-bb82-00aa00bdce0b}"

;- Class DOMMutationEvent
#CLSID_DOMMutationEvent$ = "{305106db-98b5-11cf-bb82-00aa00bdce0b}"
;- IID_IDOMBeforeUnloadEvent
#IID_IDOMBeforeUnloadEvent$ = "{30510763-98b5-11cf-bb82-00aa00bdce0b}"

;- Class DOMBeforeUnloadEvent
#CLSID_DOMBeforeUnloadEvent$ = "{30510764-98b5-11cf-bb82-00aa00bdce0b}"
;- IID_IDOMFocusEvent
#IID_IDOMFocusEvent$ = "{305106cc-98b5-11cf-bb82-00aa00bdce0b}"

;- Class DOMFocusEvent
#CLSID_DOMFocusEvent$ = "{305106cd-98b5-11cf-bb82-00aa00bdce0b}"
;- IID_IDOMCustomEvent
#IID_IDOMCustomEvent$ = "{305106de-98b5-11cf-bb82-00aa00bdce0b}"

;- Class DOMCustomEvent
#CLSID_DOMCustomEvent$ = "{305106df-98b5-11cf-bb82-00aa00bdce0b}"
;- IID_ICanvasGradient
#IID_ICanvasGradient$ = "{30510714-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_ICanvasPattern
#IID_ICanvasPattern$ = "{30510716-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_ICanvasTextMetrics
#IID_ICanvasTextMetrics$ = "{30510718-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_ICanvasImageData
#IID_ICanvasImageData$ = "{3051071a-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_ICanvasPixelArray
#IID_ICanvasPixelArray$ = "{3051071c-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLCanvasElement
#IID_IHTMLCanvasElement$ = "{305106e4-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_ICanvasRenderingContext2D
#IID_ICanvasRenderingContext2D$ = "{305106ff-98b5-11cf-bb82-00aa00bdce0b}"

;- Class CanvasGradient
#CLSID_CanvasGradient$ = "{30510715-98b5-11cf-bb82-00aa00bdce0b}"
;- Class CanvasPattern
#CLSID_CanvasPattern$ = "{30510717-98b5-11cf-bb82-00aa00bdce0b}"
;- Class CanvasTextMetrics
#CLSID_CanvasTextMetrics$ = "{30510719-98b5-11cf-bb82-00aa00bdce0b}"
;- Class CanvasImageData
#CLSID_CanvasImageData$ = "{3051071b-98b5-11cf-bb82-00aa00bdce0b}"
;- Class CanvasRenderingContext2D
#CLSID_CanvasRenderingContext2D$ = "{30510700-98b5-11cf-bb82-00aa00bdce0b}"
;- Class HTMLCanvasElement
#CLSID_HTMLCanvasElement$ = "{305106e5-98b5-11cf-bb82-00aa00bdce0b}"
;- IID_IDOMProgressEvent
#IID_IDOMProgressEvent$ = "{3051071e-98b5-11cf-bb82-00aa00bdce0b}"

;- Class DOMProgressEvent
#CLSID_DOMProgressEvent$ = "{3051071f-98b5-11cf-bb82-00aa00bdce0b}"
;- IID_IDOMMessageEvent
#IID_IDOMMessageEvent$ = "{30510720-98b5-11cf-bb82-00aa00bdce0b}"

;- Class DOMMessageEvent
#CLSID_DOMMessageEvent$ = "{30510721-98b5-11cf-bb82-00aa00bdce0b}"
;- IID_IDOMSiteModeEvent
#IID_IDOMSiteModeEvent$ = "{30510765-98b6-11cf-bb82-00aa00bdce0b}"

;- Class DOMSiteModeEvent
#CLSID_DOMSiteModeEvent$ = "{30510766-98b6-11cf-bb82-00aa00bdce0b}"
;- IID_IDOMStorageEvent
#IID_IDOMStorageEvent$ = "{30510722-98b5-11cf-bb82-00aa00bdce0b}"

;- Class DOMStorageEvent
#CLSID_DOMStorageEvent$ = "{30510723-98b5-11cf-bb82-00aa00bdce0b}"
;- IID_IXMLHttpRequestEventTarget
#IID_IXMLHttpRequestEventTarget$ = "{30510830-98b5-11cf-bb82-00aa00bdce0b}"

;- Class XMLHttpRequestEventTarget
#CLSID_XMLHttpRequestEventTarget$ = "{30510831-98b5-11cf-bb82-00aa00bdce0b}"
;- IID_IHTMLXMLHttpRequest
#IID_IHTMLXMLHttpRequest$ = "{3051040a-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLXMLHttpRequest2
#IID_IHTMLXMLHttpRequest2$ = "{30510482-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLXMLHttpRequestFactory
#IID_IHTMLXMLHttpRequestFactory$ = "{3051040c-98b5-11cf-bb82-00aa00bdce0b}"

;- Class HTMLXMLHttpRequest
#CLSID_HTMLXMLHttpRequest$ = "{3051040b-98b5-11cf-bb82-00aa00bdce0b}"
;- Class HTMLXMLHttpRequestFactory
#CLSID_HTMLXMLHttpRequestFactory$ = "{3051040d-98b5-11cf-bb82-00aa00bdce0b}"
;- Class SVGAngle
#CLSID_SVGAngle$ = "{30510584-98b5-11cf-bb82-00aa00bdce0b}"
;- IID_ISVGStringList
#IID_ISVGStringList$ = "{305104c8-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_ISVGAnimatedRect
#IID_ISVGAnimatedRect$ = "{305104d8-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_ISVGAnimatedString
#IID_ISVGAnimatedString$ = "{305104c7-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_ISVGAnimatedBoolean
#IID_ISVGAnimatedBoolean$ = "{305104c6-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_ISVGAnimatedTransformList
#IID_ISVGAnimatedTransformList$ = "{305104f9-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_ISVGTransformList
#IID_ISVGTransformList$ = "{305104f8-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_ISVGAnimatedPreserveAspectRatio
#IID_ISVGAnimatedPreserveAspectRatio$ = "{305104fb-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_ISVGPreserveAspectRatio
#IID_ISVGPreserveAspectRatio$ = "{305104fa-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_ISVGStylable
#IID_ISVGStylable$ = "{305104da-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_ISVGLocatable
#IID_ISVGLocatable$ = "{305104db-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_ISVGTransformable
#IID_ISVGTransformable$ = "{305104dc-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_ISVGTests
#IID_ISVGTests$ = "{305104dd-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_ISVGLangSpace
#IID_ISVGLangSpace$ = "{305104de-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_ISVGExternalResourcesRequired
#IID_ISVGExternalResourcesRequired$ = "{305104df-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_ISVGFitToViewBox
#IID_ISVGFitToViewBox$ = "{305104e0-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_ISVGZoomAndPan
#IID_ISVGZoomAndPan$ = "{305104e1-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_ISVGURIReference
#IID_ISVGURIReference$ = "{305104e3-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_ISVGAnimatedAngle
#IID_ISVGAnimatedAngle$ = "{305104d4-98b5-11cf-bb82-00aa00bdce0b}"

;- Class SVGAnimatedAngle
#CLSID_SVGAnimatedAngle$ = "{305105e4-98b5-11cf-bb82-00aa00bdce0b}"
;- Class SVGAnimatedTransformList
#CLSID_SVGAnimatedTransformList$ = "{305105b1-98b5-11cf-bb82-00aa00bdce0b}"
;- Class SVGAnimatedBoolean
#CLSID_SVGAnimatedBoolean$ = "{3051058b-98b5-11cf-bb82-00aa00bdce0b}"
;- Class SVGAnimatedEnumeration
#CLSID_SVGAnimatedEnumeration$ = "{3051058e-98b5-11cf-bb82-00aa00bdce0b}"
;- IID_ISVGAnimatedInteger
#IID_ISVGAnimatedInteger$ = "{305104ca-98b5-11cf-bb82-00aa00bdce0b}"

;- Class SVGAnimatedInteger
#CLSID_SVGAnimatedInteger$ = "{3051058f-98b5-11cf-bb82-00aa00bdce0b}"
;- Class SVGAnimatedLength
#CLSID_SVGAnimatedLength$ = "{30510581-98b5-11cf-bb82-00aa00bdce0b}"
;- IID_ISVGLengthList
#IID_ISVGLengthList$ = "{305104d1-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_ISVGAnimatedLengthList
#IID_ISVGAnimatedLengthList$ = "{305104d2-98b5-11cf-bb82-00aa00bdce0b}"

;- Class SVGAnimatedLengthList
#CLSID_SVGAnimatedLengthList$ = "{30510582-98b5-11cf-bb82-00aa00bdce0b}"
;- IID_ISVGAnimatedNumber
#IID_ISVGAnimatedNumber$ = "{305104cc-98b5-11cf-bb82-00aa00bdce0b}"

;- Class SVGAnimatedNumber
#CLSID_SVGAnimatedNumber$ = "{30510588-98b5-11cf-bb82-00aa00bdce0b}"
;- IID_ISVGNumberList
#IID_ISVGNumberList$ = "{305104cd-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_ISVGAnimatedNumberList
#IID_ISVGAnimatedNumberList$ = "{305104ce-98b5-11cf-bb82-00aa00bdce0b}"

;- Class SVGAnimatedNumberList
#CLSID_SVGAnimatedNumberList$ = "{3051058a-98b5-11cf-bb82-00aa00bdce0b}"
;- Class SVGAnimatedRect
#CLSID_SVGAnimatedRect$ = "{30510586-98b5-11cf-bb82-00aa00bdce0b}"
;- Class SVGAnimatedString
#CLSID_SVGAnimatedString$ = "{3051058c-98b5-11cf-bb82-00aa00bdce0b}"
;- IID_ISVGClipPathElement
#IID_ISVGClipPathElement$ = "{3051052d-98b5-11cf-bb82-00aa00bdce0b}"

;- Class SVGClipPathElement
#CLSID_SVGClipPathElement$ = "{305105e6-98b5-11cf-bb82-00aa00bdce0b}"
;- Class SVGElement
#CLSID_SVGElement$ = "{30510564-98b5-11cf-bb82-00aa00bdce0b}"
;- IID_IICCSVGColor
#IID_IICCSVGColor$ = "{305104d6-98b5-11cf-bb82-00aa00bdce0b}"

;- Class SVGLength
#CLSID_SVGLength$ = "{3051057e-98b5-11cf-bb82-00aa00bdce0b}"
;- Class SVGLengthList
#CLSID_SVGLengthList$ = "{30510580-98b5-11cf-bb82-00aa00bdce0b}"
;- Class SVGMatrix
#CLSID_SVGMatrix$ = "{305105ae-98b5-11cf-bb82-00aa00bdce0b}"
;- Class SVGNumber
#CLSID_SVGNumber$ = "{30510587-98b5-11cf-bb82-00aa00bdce0b}"
;- Class SVGNumberList
#CLSID_SVGNumberList$ = "{30510589-98b5-11cf-bb82-00aa00bdce0b}"
;- IID_ISVGPaint
#IID_ISVGPaint$ = "{30510524-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_ISVGPatternElement
#IID_ISVGPatternElement$ = "{3051052c-98b5-11cf-bb82-00aa00bdce0b}"

;- Class SVGPatternElement
#CLSID_SVGPatternElement$ = "{305105d4-98b5-11cf-bb82-00aa00bdce0b}"
;- IID_ISVGPathSeg
#IID_ISVGPathSeg$ = "{305104fc-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_ISVGPathSegArcAbs
#IID_ISVGPathSegArcAbs$ = "{30510506-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_ISVGPathSegArcRel
#IID_ISVGPathSegArcRel$ = "{30510507-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_ISVGPathSegClosePath
#IID_ISVGPathSegClosePath$ = "{305104fd-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_ISVGPathSegMovetoAbs
#IID_ISVGPathSegMovetoAbs$ = "{305104fe-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_ISVGPathSegMovetoRel
#IID_ISVGPathSegMovetoRel$ = "{305104ff-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_ISVGPathSegLinetoAbs
#IID_ISVGPathSegLinetoAbs$ = "{30510500-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_ISVGPathSegLinetoRel
#IID_ISVGPathSegLinetoRel$ = "{30510501-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_ISVGPathSegCurvetoCubicAbs
#IID_ISVGPathSegCurvetoCubicAbs$ = "{30510502-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_ISVGPathSegCurvetoCubicRel
#IID_ISVGPathSegCurvetoCubicRel$ = "{30510503-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_ISVGPathSegCurvetoCubicSmoothAbs
#IID_ISVGPathSegCurvetoCubicSmoothAbs$ = "{3051050c-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_ISVGPathSegCurvetoCubicSmoothRel
#IID_ISVGPathSegCurvetoCubicSmoothRel$ = "{3051050d-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_ISVGPathSegCurvetoQuadraticAbs
#IID_ISVGPathSegCurvetoQuadraticAbs$ = "{30510504-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_ISVGPathSegCurvetoQuadraticRel
#IID_ISVGPathSegCurvetoQuadraticRel$ = "{30510505-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_ISVGPathSegCurvetoQuadraticSmoothAbs
#IID_ISVGPathSegCurvetoQuadraticSmoothAbs$ = "{3051050e-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_ISVGPathSegCurvetoQuadraticSmoothRel
#IID_ISVGPathSegCurvetoQuadraticSmoothRel$ = "{3051050f-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_ISVGPathSegLinetoHorizontalAbs
#IID_ISVGPathSegLinetoHorizontalAbs$ = "{30510508-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_ISVGPathSegLinetoHorizontalRel
#IID_ISVGPathSegLinetoHorizontalRel$ = "{30510509-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_ISVGPathSegLinetoVerticalAbs
#IID_ISVGPathSegLinetoVerticalAbs$ = "{3051050a-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_ISVGPathSegLinetoVerticalRel
#IID_ISVGPathSegLinetoVerticalRel$ = "{3051050b-98b5-11cf-bb82-00aa00bdce0b}"

;- Class SVGPathSeg
#CLSID_SVGPathSeg$ = "{305105b3-98b5-11cf-bb82-00aa00bdce0b}"
;- Class SVGPathSegArcAbs
#CLSID_SVGPathSegArcAbs$ = "{305105bb-98b5-11cf-bb82-00aa00bdce0b}"
;- Class SVGPathSegArcRel
#CLSID_SVGPathSegArcRel$ = "{305105bc-98b5-11cf-bb82-00aa00bdce0b}"
;- Class SVGPathSegClosePath
#CLSID_SVGPathSegClosePath$ = "{305105bd-98b5-11cf-bb82-00aa00bdce0b}"
;- Class SVGPathSegMovetoAbs
#CLSID_SVGPathSegMovetoAbs$ = "{305105cc-98b5-11cf-bb82-00aa00bdce0b}"
;- Class SVGPathSegMovetoRel
#CLSID_SVGPathSegMovetoRel$ = "{305105cd-98b5-11cf-bb82-00aa00bdce0b}"
;- Class SVGPathSegLinetoAbs
#CLSID_SVGPathSegLinetoAbs$ = "{305105c6-98b5-11cf-bb82-00aa00bdce0b}"
;- Class SVGPathSegLinetoRel
#CLSID_SVGPathSegLinetoRel$ = "{305105c9-98b5-11cf-bb82-00aa00bdce0b}"
;- Class SVGPathSegCurvetoCubicAbs
#CLSID_SVGPathSegCurvetoCubicAbs$ = "{305105be-98b5-11cf-bb82-00aa00bdce0b}"
;- Class SVGPathSegCurvetoCubicRel
#CLSID_SVGPathSegCurvetoCubicRel$ = "{305105bf-98b5-11cf-bb82-00aa00bdce0b}"
;- Class SVGPathSegCurvetoCubicSmoothAbs
#CLSID_SVGPathSegCurvetoCubicSmoothAbs$ = "{305105c0-98b5-11cf-bb82-00aa00bdce0b}"
;- Class SVGPathSegCurvetoCubicSmoothRel
#CLSID_SVGPathSegCurvetoCubicSmoothRel$ = "{305105c1-98b5-11cf-bb82-00aa00bdce0b}"
;- Class SVGPathSegCurvetoQuadraticAbs
#CLSID_SVGPathSegCurvetoQuadraticAbs$ = "{305105c2-98b5-11cf-bb82-00aa00bdce0b}"
;- Class SVGPathSegCurvetoQuadraticRel
#CLSID_SVGPathSegCurvetoQuadraticRel$ = "{305105c3-98b5-11cf-bb82-00aa00bdce0b}"
;- Class SVGPathSegCurvetoQuadraticSmoothAbs
#CLSID_SVGPathSegCurvetoQuadraticSmoothAbs$ = "{305105c4-98b5-11cf-bb82-00aa00bdce0b}"
;- Class SVGPathSegCurvetoQuadraticSmoothRel
#CLSID_SVGPathSegCurvetoQuadraticSmoothRel$ = "{305105c5-98b5-11cf-bb82-00aa00bdce0b}"
;- Class SVGPathSegLinetoHorizontalAbs
#CLSID_SVGPathSegLinetoHorizontalAbs$ = "{305105c7-98b5-11cf-bb82-00aa00bdce0b}"
;- Class SVGPathSegLinetoHorizontalRel
#CLSID_SVGPathSegLinetoHorizontalRel$ = "{305105c8-98b5-11cf-bb82-00aa00bdce0b}"
;- Class SVGPathSegLinetoVerticalAbs
#CLSID_SVGPathSegLinetoVerticalAbs$ = "{305105ca-98b5-11cf-bb82-00aa00bdce0b}"
;- Class SVGPathSegLinetoVerticalRel
#CLSID_SVGPathSegLinetoVerticalRel$ = "{305105cb-98b5-11cf-bb82-00aa00bdce0b}"
;- IID_ISVGPathSegList
#IID_ISVGPathSegList$ = "{30510510-98b5-11cf-bb82-00aa00bdce0b}"

;- Class SVGPathSegList
#CLSID_SVGPathSegList$ = "{305105b4-98b5-11cf-bb82-00aa00bdce0b}"
;- Class SVGPoint
#CLSID_SVGPoint$ = "{305105ba-98b5-11cf-bb82-00aa00bdce0b}"
;- IID_ISVGPointList
#IID_ISVGPointList$ = "{305104f5-98b5-11cf-bb82-00aa00bdce0b}"

;- Class SVGPointList
#CLSID_SVGPointList$ = "{305105b9-98b5-11cf-bb82-00aa00bdce0b}"
;- Class SVGRect
#CLSID_SVGRect$ = "{30510583-98b5-11cf-bb82-00aa00bdce0b}"
;- Class SVGStringList
#CLSID_SVGStringList$ = "{3051058d-98b5-11cf-bb82-00aa00bdce0b}"
;- Class SVGTransform
#CLSID_SVGTransform$ = "{305105af-98b5-11cf-bb82-00aa00bdce0b}"
;- Class SVGSVGElement
#CLSID_SVGSVGElement$ = "{30510574-98b5-11cf-bb82-00aa00bdce0b}"
;- IID_ISVGElementInstance
#IID_ISVGElementInstance$ = "{305104ee-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_ISVGUseElement
#IID_ISVGUseElement$ = "{305104ed-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_ISVGElementInstanceList
#IID_ISVGElementInstanceList$ = "{305104ef-98b5-11cf-bb82-00aa00bdce0b}"

;- Class SVGUseElement
#CLSID_SVGUseElement$ = "{30510590-98b5-11cf-bb82-00aa00bdce0b}"
;- Class HTMLStyleSheetRulesAppliedCollection
#CLSID_HTMLStyleSheetRulesAppliedCollection$ = "{eb36f845-2395-4719-b85c-d0d80e184bd9}"
;- Class RulesApplied
#CLSID_RulesApplied$ = "{7c803920-7a53-4d26-98ac-fdd23e6b9e01}"
;- Class RulesAppliedCollection
#CLSID_RulesAppliedCollection$ = "{671926ee-c3cf-40af-be8f-1cbaee6486e8}"
;- Class HTMLW3CComputedStyle
#CLSID_HTMLW3CComputedStyle$ = "{305106c8-98b5-11cf-bb82-00aa00bdce0b}"
;- Class SVGTransformList
#CLSID_SVGTransformList$ = "{305105b0-98b5-11cf-bb82-00aa00bdce0b}"
;- IID_ISVGAnimatedPoints
#IID_ISVGAnimatedPoints$ = "{30510517-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_ISVGCircleElement
#IID_ISVGCircleElement$ = "{30510514-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_ISVGEllipseElement
#IID_ISVGEllipseElement$ = "{30510515-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_ISVGLineElement
#IID_ISVGLineElement$ = "{30510516-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_ISVGRectElement
#IID_ISVGRectElement$ = "{30510513-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_ISVGPolygonElement
#IID_ISVGPolygonElement$ = "{30510519-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_ISVGPolylineElement
#IID_ISVGPolylineElement$ = "{30510518-98b5-11cf-bb82-00aa00bdce0b}"

;- Class SVGCircleElement
#CLSID_SVGCircleElement$ = "{30510578-98b5-11cf-bb82-00aa00bdce0b}"
;- Class SVGEllipseElement
#CLSID_SVGEllipseElement$ = "{30510579-98b5-11cf-bb82-00aa00bdce0b}"
;- Class SVGLineElement
#CLSID_SVGLineElement$ = "{3051057a-98b5-11cf-bb82-00aa00bdce0b}"
;- Class SVGRectElement
#CLSID_SVGRectElement$ = "{30510577-98b5-11cf-bb82-00aa00bdce0b}"
;- Class SVGPolygonElement
#CLSID_SVGPolygonElement$ = "{3051057b-98b5-11cf-bb82-00aa00bdce0b}"
;- Class SVGPolylineElement
#CLSID_SVGPolylineElement$ = "{3051057c-98b5-11cf-bb82-00aa00bdce0b}"
;- IID_ISVGGElement
#IID_ISVGGElement$ = "{305104e8-98b5-11cf-bb82-00aa00bdce0b}"

;- Class SVGGElement
#CLSID_SVGGElement$ = "{3051056f-98b5-11cf-bb82-00aa00bdce0b}"
;- IID_ISVGSymbolElement
#IID_ISVGSymbolElement$ = "{305104ec-98b5-11cf-bb82-00aa00bdce0b}"

;- Class SVGSymbolElement
#CLSID_SVGSymbolElement$ = "{30510571-98b5-11cf-bb82-00aa00bdce0b}"
;- IID_ISVGDefsElement
#IID_ISVGDefsElement$ = "{305104e9-98b5-11cf-bb82-00aa00bdce0b}"

;- Class SVGDefsElement
#CLSID_SVGDefsElement$ = "{30510570-98b5-11cf-bb82-00aa00bdce0b}"
;- IID_ISVGAnimatedPathData
#IID_ISVGAnimatedPathData$ = "{30510511-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_ISVGPathElement
#IID_ISVGPathElement$ = "{30510512-98b5-11cf-bb82-00aa00bdce0b}"

;- Class SVGPathElement
#CLSID_SVGPathElement$ = "{305105b2-98b5-11cf-bb82-00aa00bdce0b}"
;- Class SVGPreserveAspectRatio
#CLSID_SVGPreserveAspectRatio$ = "{305105d0-98b5-11cf-bb82-00aa00bdce0b}"
;- IID_ISVGTextElement
#IID_ISVGTextElement$ = "{3051051c-98b5-11cf-bb82-00aa00bdce0b}"

;- Class SVGTextElement
#CLSID_SVGTextElement$ = "{305105df-98b5-11cf-bb82-00aa00bdce0b}"
;- IID_ISVGTextPositioningElement
#IID_ISVGTextPositioningElement$ = "{3051051b-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_ISVGTextContentElement
#IID_ISVGTextContentElement$ = "{3051051a-98b5-11cf-bb82-00aa00bdce0b}"

;- Class SVGAnimatedPreserveAspectRatio
#CLSID_SVGAnimatedPreserveAspectRatio$ = "{305105ce-98b5-11cf-bb82-00aa00bdce0b}"
;- IID_ISVGImageElement
#IID_ISVGImageElement$ = "{305104f0-98b5-11cf-bb82-00aa00bdce0b}"

;- Class SVGImageElement
#CLSID_SVGImageElement$ = "{305105cf-98b5-11cf-bb82-00aa00bdce0b}"
;- IID_ISVGStopElement
#IID_ISVGStopElement$ = "{3051052b-98b5-11cf-bb82-00aa00bdce0b}"

;- Class SVGStopElement
#CLSID_SVGStopElement$ = "{305105d5-98b5-11cf-bb82-00aa00bdce0b}"
;- IID_ISVGGradientElement
#IID_ISVGGradientElement$ = "{30510528-98b5-11cf-bb82-00aa00bdce0b}"

;- Class SVGGradientElement
#CLSID_SVGGradientElement$ = "{305105d6-98b5-11cf-bb82-00aa00bdce0b}"
;- IID_ISVGLinearGradientElement
#IID_ISVGLinearGradientElement$ = "{30510529-98b5-11cf-bb82-00aa00bdce0b}"

;- Class SVGLinearGradientElement
#CLSID_SVGLinearGradientElement$ = "{305105d2-98b5-11cf-bb82-00aa00bdce0b}"
;- IID_ISVGRadialGradientElement
#IID_ISVGRadialGradientElement$ = "{3051052a-98b5-11cf-bb82-00aa00bdce0b}"

;- Class SVGRadialGradientElement
#CLSID_SVGRadialGradientElement$ = "{305105d3-98b5-11cf-bb82-00aa00bdce0b}"
;- IID_ISVGMaskElement
#IID_ISVGMaskElement$ = "{3051052e-98b5-11cf-bb82-00aa00bdce0b}"

;- Class SVGMaskElement
#CLSID_SVGMaskElement$ = "{305105e7-98b5-11cf-bb82-00aa00bdce0b}"
;- IID_ISVGMarkerElement
#IID_ISVGMarkerElement$ = "{30510525-98b5-11cf-bb82-00aa00bdce0b}"

;- Class SVGMarkerElement
#CLSID_SVGMarkerElement$ = "{305105de-98b5-11cf-bb82-00aa00bdce0b}"
;- IID_ISVGZoomEvent
#IID_ISVGZoomEvent$ = "{3051054e-98b5-11cf-bb82-00aa00bdce0b}"

;- Class SVGZoomEvent
#CLSID_SVGZoomEvent$ = "{305105d9-98b5-11cf-bb82-00aa00bdce0b}"
;- IID_ISVGAElement
#IID_ISVGAElement$ = "{3051054b-98b5-11cf-bb82-00aa00bdce0b}"

;- Class SVGAElement
#CLSID_SVGAElement$ = "{305105db-98b5-11cf-bb82-00aa00bdce0b}"
;- IID_ISVGViewElement
#IID_ISVGViewElement$ = "{3051054c-98b5-11cf-bb82-00aa00bdce0b}"

;- Class SVGViewElement
#CLSID_SVGViewElement$ = "{305105dc-98b5-11cf-bb82-00aa00bdce0b}"
;- IID_IHTMLMediaError
#IID_IHTMLMediaError$ = "{30510704-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLTimeRanges
#IID_IHTMLTimeRanges$ = "{30510705-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLTimeRanges2
#IID_IHTMLTimeRanges2$ = "{3051080b-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLMediaElement
#IID_IHTMLMediaElement$ = "{30510706-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLMediaElement2
#IID_IHTMLMediaElement2$ = "{30510809-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLMSMediaElement
#IID_IHTMLMSMediaElement$ = "{30510792-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLSourceElement
#IID_IHTMLSourceElement$ = "{30510707-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLAudioElement
#IID_IHTMLAudioElement$ = "{30510708-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLVideoElement
#IID_IHTMLVideoElement$ = "{30510709-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLAudioElementFactory
#IID_IHTMLAudioElementFactory$ = "{305107eb-98b5-11cf-bb82-00aa00bdce0b}"

;- Class HTMLMediaError
#CLSID_HTMLMediaError$ = "{3051070a-98b5-11cf-bb82-00aa00bdce0b}"
;- Class HTMLTimeRanges
#CLSID_HTMLTimeRanges$ = "{3051070b-98b5-11cf-bb82-00aa00bdce0b}"
;- Class HTMLMediaElement
#CLSID_HTMLMediaElement$ = "{3051070c-98b5-11cf-bb82-00aa00bdce0b}"
;- Class HTMLSourceElement
#CLSID_HTMLSourceElement$ = "{3051070d-98b5-11cf-bb82-00aa00bdce0b}"
;- Class HTMLAudioElement
#CLSID_HTMLAudioElement$ = "{3051070e-98b5-11cf-bb82-00aa00bdce0b}"
;- Class HTMLAudioElementFactory
#CLSID_HTMLAudioElementFactory$ = "{305107ec-98b5-11cf-bb82-00aa00bdce0b}"
;- Class HTMLVideoElement
#CLSID_HTMLVideoElement$ = "{3051070f-98b5-11cf-bb82-00aa00bdce0b}"
;- IID_ISVGSwitchElement
#IID_ISVGSwitchElement$ = "{305104f1-98b5-11cf-bb82-00aa00bdce0b}"

;- Class SVGSwitchElement
#CLSID_SVGSwitchElement$ = "{305105d8-98b5-11cf-bb82-00aa00bdce0b}"
;- IID_ISVGDescElement
#IID_ISVGDescElement$ = "{305104ea-98b5-11cf-bb82-00aa00bdce0b}"

;- Class SVGDescElement
#CLSID_SVGDescElement$ = "{30510572-98b5-11cf-bb82-00aa00bdce0b}"
;- IID_ISVGTitleElement
#IID_ISVGTitleElement$ = "{305104eb-98b5-11cf-bb82-00aa00bdce0b}"

;- Class SVGTitleElement
#CLSID_SVGTitleElement$ = "{30510573-98b5-11cf-bb82-00aa00bdce0b}"
;- IID_ISVGMetadataElement
#IID_ISVGMetadataElement$ = "{30510560-98b5-11cf-bb82-00aa00bdce0b}"

;- Class SVGMetadataElement
#CLSID_SVGMetadataElement$ = "{305105d7-98b5-11cf-bb82-00aa00bdce0b}"
;- Class SVGElementInstance
#CLSID_SVGElementInstance$ = "{30510575-98b5-11cf-bb82-00aa00bdce0b}"
;- Class SVGElementInstanceList
#CLSID_SVGElementInstanceList$ = "{30510576-98b5-11cf-bb82-00aa00bdce0b}"
;- IID_IDOMException
#IID_IDOMException$ = "{3051072b-98b5-11cf-bb82-00aa00bdce0b}"

;- Class DOMException
#CLSID_DOMException$ = "{3051072c-98b5-11cf-bb82-00aa00bdce0b}"
;- IID_IRangeException
#IID_IRangeException$ = "{3051072d-98b5-11cf-bb82-00aa00bdce0b}"

;- Class RangeException
#CLSID_RangeException$ = "{3051072e-98b5-11cf-bb82-00aa00bdce0b}"
;- IID_ISVGException
#IID_ISVGException$ = "{3051072f-98b5-11cf-bb82-00aa00bdce0b}"

;- Class SVGException
#CLSID_SVGException$ = "{30510730-98b5-11cf-bb82-00aa00bdce0b}"
;- IID_IEventException
#IID_IEventException$ = "{3051073a-98b5-11cf-bb82-00aa00bdce0b}"

;- Class EventException
#CLSID_EventException$ = "{3051073b-98b5-11cf-bb82-00aa00bdce0b}"
;- IID_ISVGScriptElement
#IID_ISVGScriptElement$ = "{3051054d-98b5-11cf-bb82-00aa00bdce0b}"

;- Class SVGScriptElement
#CLSID_SVGScriptElement$ = "{305105e1-98b5-11cf-bb82-00aa00bdce0b}"
;- IID_ISVGStyleElement
#IID_ISVGStyleElement$ = "{305104f3-98b5-11cf-bb82-00aa00bdce0b}"

;- Class SVGStyleElement
#CLSID_SVGStyleElement$ = "{305105d1-98b5-11cf-bb82-00aa00bdce0b}"
;- Class SVGTextContentElement
#CLSID_SVGTextContentElement$ = "{305105dd-98b5-11cf-bb82-00aa00bdce0b}"
;- Class SVGTextPositioningElement
#CLSID_SVGTextPositioningElement$ = "{305105e0-98b5-11cf-bb82-00aa00bdce0b}"
;- Class DOMDocumentType
#CLSID_DOMDocumentType$ = "{30510739-98b5-11cf-bb82-00aa00bdce0b}"
;- Class NodeIterator
#CLSID_NodeIterator$ = "{30510745-98b5-11cf-bb82-00aa00bdce0b}"
;- Class TreeWalker
#CLSID_TreeWalker$ = "{30510747-98b5-11cf-bb82-00aa00bdce0b}"
;- Class DOMProcessingInstruction
#CLSID_DOMProcessingInstruction$ = "{30510743-98b5-11cf-bb82-00aa00bdce0b}"
;- Class HTMLPerformance
#CLSID_HTMLPerformance$ = "{3051074f-98b5-11cf-bb82-00aa00bdce0b}"
;- Class HTMLPerformanceNavigation
#CLSID_HTMLPerformanceNavigation$ = "{30510751-98b5-11cf-bb82-00aa00bdce0b}"
;- Class HTMLPerformanceTiming
#CLSID_HTMLPerformanceTiming$ = "{30510753-98b5-11cf-bb82-00aa00bdce0b}"
;- IID_ISVGTSpanElement
#IID_ISVGTSpanElement$ = "{3051051d-98b5-11cf-bb82-00aa00bdce0b}"

;- Class SVGTSpanElement
#CLSID_SVGTSpanElement$ = "{305105e2-98b5-11cf-bb82-00aa00bdce0b}"
;- IID_ITemplatePrinter
#IID_ITemplatePrinter$ = "{3050f6b4-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_ITemplatePrinter2
#IID_ITemplatePrinter2$ = "{3050f83f-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_ITemplatePrinter3
#IID_ITemplatePrinter3$ = "{305104a3-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IPrintManagerTemplatePrinter
#IID_IPrintManagerTemplatePrinter$ = "{f633be14-9eff-4c4d-929e-05717b21b3e6}"

;- IID_IPrintManagerTemplatePrinter2
#IID_IPrintManagerTemplatePrinter2$ = "{c6403497-7493-4f09-8016-54b03e9bda69}"

;- Class CTemplatePrinter
#CLSID_CTemplatePrinter$ = "{3050f6b3-98b5-11cf-bb82-00aa00bdce0b}"
;- Class CPrintManagerTemplatePrinter
#CLSID_CPrintManagerTemplatePrinter$ = "{63619f54-9d71-4c23-a08d-50d7f18db2e9}"
;- IID_ISVGTextPathElement
#IID_ISVGTextPathElement$ = "{3051051f-98b5-11cf-bb82-00aa00bdce0b}"

;- Class SVGTextPathElement
#CLSID_SVGTextPathElement$ = "{305105eb-98b5-11cf-bb82-00aa00bdce0b}"
;- IID_IDOMXmlSerializer
#IID_IDOMXmlSerializer$ = "{3051077d-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IDOMParser
#IID_IDOMParser$ = "{30510781-98b5-11cf-bb82-00aa00bdce0b}"

;- Class XMLSerializer
#CLSID_XMLSerializer$ = "{3051077e-98b5-11cf-bb82-00aa00bdce0b}"
;- Class DOMParser
#CLSID_DOMParser$ = "{30510782-98b5-11cf-bb82-00aa00bdce0b}"
;- IID_IDOMXmlSerializerFactory
#IID_IDOMXmlSerializerFactory$ = "{3051077f-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IDOMParserFactory
#IID_IDOMParserFactory$ = "{30510783-98b5-11cf-bb82-00aa00bdce0b}"

;- Class HTMLDOMXmlSerializerFactory
#CLSID_HTMLDOMXmlSerializerFactory$ = "{30510780-98b5-11cf-bb82-00aa00bdce0b}"
;- Class DOMParserFactory
#CLSID_DOMParserFactory$ = "{30510784-98b5-11cf-bb82-00aa00bdce0b}"
;- Class HTMLSemanticElement
#CLSID_HTMLSemanticElement$ = "{305107b0-98b5-11cf-bb82-00aa00bdce0b}"
;- IID_IHTMLProgressElement
#IID_IHTMLProgressElement$ = "{3050f2d6-98b5-11cf-bb82-00aa00bdce0b}"

;- Class HTMLProgressElement
#CLSID_HTMLProgressElement$ = "{3050f2d5-98b5-11cf-bb82-00aa00bdce0b}"
;- IID_IDOMMSTransitionEvent
#IID_IDOMMSTransitionEvent$ = "{305107b5-98b5-11cf-bb82-00aa00bdce0b}"

;- Class DOMMSTransitionEvent
#CLSID_DOMMSTransitionEvent$ = "{305107b6-98b5-11cf-bb82-00aa00bdce0b}"
;- IID_IDOMMSAnimationEvent
#IID_IDOMMSAnimationEvent$ = "{305107b7-98b5-11cf-bb82-00aa00bdce0b}"

;- Class DOMMSAnimationEvent
#CLSID_DOMMSAnimationEvent$ = "{305107b8-98b5-11cf-bb82-00aa00bdce0b}"
;- IID_IWebGeocoordinates
#IID_IWebGeocoordinates$ = "{305107c7-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IWebGeopositionError
#IID_IWebGeopositionError$ = "{305107c9-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IWebGeoposition
#IID_IWebGeoposition$ = "{305107cd-98b5-11cf-bb82-00aa00bdce0b}"

;- Class WebGeolocation
#CLSID_WebGeolocation$ = "{305107c6-98b5-11cf-bb82-00aa00bdce0b}"
;- Class WebGeocoordinates
#CLSID_WebGeocoordinates$ = "{305107c8-98b5-11cf-bb82-00aa00bdce0b}"
;- Class WebGeopositionError
#CLSID_WebGeopositionError$ = "{305107ca-98b5-11cf-bb82-00aa00bdce0b}"
;- Class WebGeoposition
#CLSID_WebGeoposition$ = "{305107ce-98b5-11cf-bb82-00aa00bdce0b}"
;- IID_IClientCaps
#IID_IClientCaps$ = "{7e8bc44d-aeff-11d1-89c2-00c04fb6bfc4}"

;- Class CClientCaps
#CLSID_CClientCaps$ = "{7e8bc44e-aeff-11d1-89c2-00c04fb6bfc4}"
;- IID_IDOMMSManipulationEvent
#IID_IDOMMSManipulationEvent$ = "{30510816-98b5-11cf-bb82-00aa00bdce0b}"

;- Class DOMMSManipulationEvent
#CLSID_DOMMSManipulationEvent$ = "{30510817-98b5-11cf-bb82-00aa00bdce0b}"
;- IID_IDOMCloseEvent
#IID_IDOMCloseEvent$ = "{305107ff-98b5-11cf-bb82-00aa00bdce0b}"

;- Class DOMCloseEvent
#CLSID_DOMCloseEvent$ = "{30510800-98b5-11cf-bb82-00aa00bdce0b}"
;- Class applicationCache
#CLSID_applicationCache$ = "{30510829-98b5-11cf-bb82-00aa00bdce0b}"
;- IID_ICSSFilterSite
#IID_ICSSFilterSite$ = "{3050f3ed-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IMarkupPointer
#IID_IMarkupPointer$ = "{3050f49f-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IMarkupContainer
#IID_IMarkupContainer$ = "{3050f5f9-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IMarkupContainer2
#IID_IMarkupContainer2$ = "{3050f648-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLChangeSink
#IID_IHTMLChangeSink$ = "{3050f64a-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLChangeLog
#IID_IHTMLChangeLog$ = "{3050f649-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IActiveIMMApp
#IID_IActiveIMMApp$ = "{08c0e040-62d1-11d1-9326-0060b067b86e}"

;- IID_IEnumRegisterWordA
#IID_IEnumRegisterWordA$ = "{08c03412-f96b-11d0-a475-00aa006bcc59}"

;- IID_IEnumRegisterWordW
#IID_IEnumRegisterWordW$ = "{4955dd31-b159-11d0-8fcf-00aa006bcc59}"

;- IID_IEnumInputContext
#IID_IEnumInputContext$ = "{09b5eab0-f997-11d1-93d4-0060b067b86e}"

;- IID_ISegmentList
#IID_ISegmentList$ = "{3050f605-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_ISegmentListIterator
#IID_ISegmentListIterator$ = "{3050f692-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_ISegment
#IID_ISegment$ = "{3050f683-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLCaret
#IID_IHTMLCaret$ = "{3050f604-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IDisplayPointer
#IID_IDisplayPointer$ = "{3050f69e-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_ILineInfo
#IID_ILineInfo$ = "{3050f7e2-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IElementSegment
#IID_IElementSegment$ = "{3050f68f-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHighlightSegment
#IID_IHighlightSegment$ = "{3050f690-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHighlightRenderingServices
#IID_IHighlightRenderingServices$ = "{3050f606-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IDisplayServices
#IID_IDisplayServices$ = "{3050f69d-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLComputedStyle
#IID_IHTMLComputedStyle$ = "{3050f6c3-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHtmlDlgSafeHelper
#IID_IHtmlDlgSafeHelper$ = "{3050f81a-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IBlockFormats
#IID_IBlockFormats$ = "{3050f830-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IFontNames
#IID_IFontNames$ = "{3050f839-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_ICSSFilter
#IID_ICSSFilter$ = "{3050f3ec-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_ISecureUrlHost
#IID_ISecureUrlHost$ = "{c81984c4-74c8-11d2-baa9-00c04fc2040e}"

;- IID_IMarkupServices
#IID_IMarkupServices$ = "{3050f4a0-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IMarkupServices2
#IID_IMarkupServices2$ = "{3050f682-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLChangePlayback
#IID_IHTMLChangePlayback$ = "{3050f6e0-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IMarkupPointer2
#IID_IMarkupPointer2$ = "{3050f675-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IMarkupTextFrags
#IID_IMarkupTextFrags$ = "{3050f5fa-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IXMLGenericParse
#IID_IXMLGenericParse$ = "{e4e23071-4d07-11d2-ae76-0080c73bc199}"

;- IID_IHTMLEditHost
#IID_IHTMLEditHost$ = "{3050f6a0-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLEditHost2
#IID_IHTMLEditHost2$ = "{3050f848-98b5-11cf-bb82-00aa00bdce0d}"

;- IID_ISequenceNumber
#IID_ISequenceNumber$ = "{3050f6c1-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IIMEServices
#IID_IIMEServices$ = "{3050f6ca-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_ISelectionServicesListener
#IID_ISelectionServicesListener$ = "{3050f699-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_ISelectionServices
#IID_ISelectionServices$ = "{3050f684-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLEditDesigner
#IID_IHTMLEditDesigner$ = "{3050f662-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLEditServices
#IID_IHTMLEditServices$ = "{3050f663-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLEditServices2
#IID_IHTMLEditServices2$ = "{3050f812-98b5-11cf-bb82-00aa00bdce0b}"

;- Class HtmlDlgSafeHelper
#CLSID_HtmlDlgSafeHelper$ = "{3050f819-98b5-11cf-bb82-00aa00bdce0b}"
;- Class BlockFormats
#CLSID_BlockFormats$ = "{3050f831-98b5-11cf-bb82-00aa00bdce0b}"
;- Class FontNames
#CLSID_FontNames$ = "{3050f83a-98b5-11cf-bb82-00aa00bdce0b}"
;- IID_IDeveloperConsoleMessageReceiver
#IID_IDeveloperConsoleMessageReceiver$ = "{30510808-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IScriptEventHandler
#IID_IScriptEventHandler$ = "{3051083a-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IDebugCallbackNotificationHandler
#IID_IDebugCallbackNotificationHandler$ = "{30510842-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IScriptEventHandlerSourceInfo
#IID_IScriptEventHandlerSourceInfo$ = "{30510841-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IDOMEventRegistrationCallback
#IID_IDOMEventRegistrationCallback$ = "{3051083b-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IEventTarget2
#IID_IEventTarget2$ = "{30510839-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLNamespace
#IID_IHTMLNamespace$ = "{3050f6bb-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLNamespaceCollection
#IID_IHTMLNamespaceCollection$ = "{3050f6b8-98b5-11cf-bb82-00aa00bdce0b}"

;- Class HTMLNamespace
#CLSID_HTMLNamespace$ = "{3050f6bc-98b5-11cf-bb82-00aa00bdce0b}"
;- Class HTMLNamespaceCollection
#CLSID_HTMLNamespaceCollection$ = "{3050f6b9-98b5-11cf-bb82-00aa00bdce0b}"
;- IID_IHTMLPainter
#IID_IHTMLPainter$ = "{3050f6a6-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLPaintSite
#IID_IHTMLPaintSite$ = "{3050f6a7-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLPainterEventInfo
#IID_IHTMLPainterEventInfo$ = "{3050f6df-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLPainterOverlay
#IID_IHTMLPainterOverlay$ = "{3050f7e3-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLIPrintCollection
#IID_IHTMLIPrintCollection$ = "{3050f6b5-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IEnumPrivacyRecords
#IID_IEnumPrivacyRecords$ = "{3050f844-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IWPCBlockedUrls
#IID_IWPCBlockedUrls$ = "{30510413-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLDOMConstructorCollection
#IID_IHTMLDOMConstructorCollection$ = "{3051049c-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLDialog
#IID_IHTMLDialog$ = "{3050f216-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLDialog2
#IID_IHTMLDialog2$ = "{3050f5e0-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLDialog3
#IID_IHTMLDialog3$ = "{3050f388-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLModelessInit
#IID_IHTMLModelessInit$ = "{3050f5e4-98b5-11cf-bb82-00aa00bdce0b}"

;- Class ThreadDialogProcParam
#CLSID_ThreadDialogProcParam$ = "{3050f5eb-98b5-11cf-bb82-00aa00bdce0b}"
;- Class HTMLDialog
#CLSID_HTMLDialog$ = "{3050f28a-98b5-11cf-bb82-00aa00bdce0b}"
;- IID_IHTMLPopup
#IID_IHTMLPopup$ = "{3050f666-98b5-11cf-bb82-00aa00bdce0b}"

;- Class HTMLPopup
#CLSID_HTMLPopup$ = "{3050f667-98b5-11cf-bb82-00aa00bdce0b}"
;- IID_IHTMLAppBehavior
#IID_IHTMLAppBehavior$ = "{3050f5ca-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLAppBehavior2
#IID_IHTMLAppBehavior2$ = "{3050f5c9-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHTMLAppBehavior3
#IID_IHTMLAppBehavior3$ = "{3050f5cd-98b5-11cf-bb82-00aa00bdce0b}"

;- Class HTMLAppBehavior
#CLSID_HTMLAppBehavior$ = "{3050f5cb-98b5-11cf-bb82-00aa00bdce0b}"
;- Class OldHTMLDocument
#CLSID_OldHTMLDocument$ = "{d48a6ec9-6a4a-11cf-94a7-444553540000}"
;- Class OldHTMLFormElement
#CLSID_OldHTMLFormElement$ = "{0d04d285-6bec-11cf-8b97-00aa00476da6}"
;- Class HTMLInputButtonElement
#CLSID_HTMLInputButtonElement$ = "{3050f2b4-98b5-11cf-bb82-00aa00bdce0b}"
;- Class HTMLInputTextElement
#CLSID_HTMLInputTextElement$ = "{3050f2ab-98b5-11cf-bb82-00aa00bdce0b}"
;- Class HTMLInputFileElement
#CLSID_HTMLInputFileElement$ = "{3050f2ae-98b5-11cf-bb82-00aa00bdce0b}"
;- Class HTMLOptionButtonElement
#CLSID_HTMLOptionButtonElement$ = "{3050f2be-98b5-11cf-bb82-00aa00bdce0b}"
;- Class htmlInputImage
#CLSID_htmlInputImage$ = "{3050f2c4-98b5-11cf-bb82-00aa00bdce0b}"
;- IID_IElementNamespace
#IID_IElementNamespace$ = "{3050f671-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IElementNamespaceTable
#IID_IElementNamespaceTable$ = "{3050f670-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IElementNamespaceFactory
#IID_IElementNamespaceFactory$ = "{3050f672-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IElementNamespaceFactory2
#IID_IElementNamespaceFactory2$ = "{3050f805-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IElementNamespaceFactoryCallback
#IID_IElementNamespaceFactoryCallback$ = "{3050f7fd-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IElementBehaviorSiteOM2
#IID_IElementBehaviorSiteOM2$ = "{3050f659-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IElementBehaviorCategory
#IID_IElementBehaviorCategory$ = "{3050f4ed-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IElementBehaviorSiteCategory
#IID_IElementBehaviorSiteCategory$ = "{3050f4ee-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IEnumUnknown
#IID_IEnumUnknown$ = "{00000100-0000-0000-c000-000000000046}"

;- IID_IElementBehaviorSubmit
#IID_IElementBehaviorSubmit$ = "{3050f646-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IElementBehaviorFocus
#IID_IElementBehaviorFocus$ = "{3050f6b6-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IElementBehaviorLayout
#IID_IElementBehaviorLayout$ = "{3050f6ba-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IElementBehaviorLayout2
#IID_IElementBehaviorLayout2$ = "{3050f846-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IElementBehaviorSiteLayout
#IID_IElementBehaviorSiteLayout$ = "{3050f6b7-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IElementBehaviorSiteLayout2
#IID_IElementBehaviorSiteLayout2$ = "{3050f847-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IHostBehaviorInit
#IID_IHostBehaviorInit$ = "{3050f842-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_ISurfacePresenter
#IID_ISurfacePresenter$ = "{305106e2-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IViewObjectPresentSite
#IID_IViewObjectPresentSite$ = "{305106e1-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_ICanvasPixelArrayData
#IID_ICanvasPixelArrayData$ = "{305107f9-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IViewObjectPrint
#IID_IViewObjectPrint$ = "{305106e3-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IViewObjectPresentNotifySite
#IID_IViewObjectPresentNotifySite$ = "{305107fa-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IViewObjectPresentNotify
#IID_IViewObjectPresentNotify$ = "{305107f8-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_ITrackingProtection
#IID_ITrackingProtection$ = "{30510803-98b5-11cf-bb82-00aa00bdce0b}"

;- IID_IBFCacheable
#IID_IBFCacheable$ = "{30510861-98b5-11cf-bb82-00aa00bdce0b}"

