;Generated by PB Type Library Importer Version: 1.0
;msxml6.dll
;msxml6_iid_str.pbi

;- IID_IXMLDOMNode
#IID_IXMLDOMNode$ = "{2933bf80-7b36-11d2-b20e-00c04f983e60}"

;- IID_IXMLDOMNodeList
#IID_IXMLDOMNodeList$ = "{2933bf82-7b36-11d2-b20e-00c04f983e60}"

;- IID_IXMLDOMNamedNodeMap
#IID_IXMLDOMNamedNodeMap$ = "{2933bf83-7b36-11d2-b20e-00c04f983e60}"

;- IID_IXMLDOMDocumentType
#IID_IXMLDOMDocumentType$ = "{2933bf8b-7b36-11d2-b20e-00c04f983e60}"

;- IID_IXMLDOMImplementation
#IID_IXMLDOMImplementation$ = "{2933bf8f-7b36-11d2-b20e-00c04f983e60}"

;- IID_IXMLDOMElement
#IID_IXMLDOMElement$ = "{2933bf86-7b36-11d2-b20e-00c04f983e60}"

;- IID_IXMLDOMAttribute
#IID_IXMLDOMAttribute$ = "{2933bf85-7b36-11d2-b20e-00c04f983e60}"

;- IID_IXMLDOMDocumentFragment
#IID_IXMLDOMDocumentFragment$ = "{3efaa413-272f-11d2-836f-0000f87a7782}"

;- IID_IXMLDOMText
#IID_IXMLDOMText$ = "{2933bf87-7b36-11d2-b20e-00c04f983e60}"

;- IID_IXMLDOMCharacterData
#IID_IXMLDOMCharacterData$ = "{2933bf84-7b36-11d2-b20e-00c04f983e60}"

;- IID_IXMLDOMComment
#IID_IXMLDOMComment$ = "{2933bf88-7b36-11d2-b20e-00c04f983e60}"

;- IID_IXMLDOMCDATASection
#IID_IXMLDOMCDATASection$ = "{2933bf8a-7b36-11d2-b20e-00c04f983e60}"

;- IID_IXMLDOMProcessingInstruction
#IID_IXMLDOMProcessingInstruction$ = "{2933bf89-7b36-11d2-b20e-00c04f983e60}"

;- IID_IXMLDOMEntityReference
#IID_IXMLDOMEntityReference$ = "{2933bf8e-7b36-11d2-b20e-00c04f983e60}"

;- IID_IXMLDOMParseError
#IID_IXMLDOMParseError$ = "{3efaa426-272f-11d2-836f-0000f87a7782}"

;- IID_IXMLDOMNotation
#IID_IXMLDOMNotation$ = "{2933bf8c-7b36-11d2-b20e-00c04f983e60}"

;- IID_IXMLDOMEntity
#IID_IXMLDOMEntity$ = "{2933bf8d-7b36-11d2-b20e-00c04f983e60}"

;- IID_IXMLDOMParseError2
#IID_IXMLDOMParseError2$ = "{3efaa428-272f-11d2-836f-0000f87a7782}"

;- IID_IXMLDOMParseErrorCollection
#IID_IXMLDOMParseErrorCollection$ = "{3efaa429-272f-11d2-836f-0000f87a7782}"

;- IID_IXTLRuntime
#IID_IXTLRuntime$ = "{3efaa425-272f-11d2-836f-0000f87a7782}"

;- IID_IVBSAXXMLFilter
#IID_IVBSAXXMLFilter$ = "{1299eb1b-5b88-433e-82de-82ca75ad4e04}"

;- IID_IVBSAXXMLReader
#IID_IVBSAXXMLReader$ = "{8c033caa-6cd6-4f73-b728-4531af74945f}"

;- IID_IVBSAXEntityResolver
#IID_IVBSAXEntityResolver$ = "{0c05d096-f45b-4aca-ad1a-aa0bc25518dc}"

;- IID_IVBSAXContentHandler
#IID_IVBSAXContentHandler$ = "{2ed7290a-4dd5-4b46-bb26-4e4155e77faa}"

;- IID_IVBSAXLocator
#IID_IVBSAXLocator$ = "{796e7ac5-5aa2-4eff-acad-3faaf01a3288}"

;- IID_IVBSAXAttributes
#IID_IVBSAXAttributes$ = "{10dc0586-132b-4cac-8bb3-db00ac8b7ee0}"

;- IID_IVBSAXDTDHandler
#IID_IVBSAXDTDHandler$ = "{24fb3297-302d-4620-ba39-3a732d850558}"

;- IID_IVBSAXErrorHandler
#IID_IVBSAXErrorHandler$ = "{d963d3fe-173c-4862-9095-b92f66995f52}"

;- IID_IMXReaderControl
#IID_IMXReaderControl$ = "{808f4e35-8d5a-4fbe-8466-33a41279ed30}"

;- IID_IMXSchemaDeclHandler
#IID_IMXSchemaDeclHandler$ = "{fa4bb38c-faf9-4cca-9302-d1dd0fe520db}"

;- IID_ISchemaElement
#IID_ISchemaElement$ = "{50ea08b7-dd1b-4664-9a50-c2f40f4bd79a}"

;- IID_ISchemaParticle
#IID_ISchemaParticle$ = "{50ea08b5-dd1b-4664-9a50-c2f40f4bd79a}"

;- IID_ISchemaItem
#IID_ISchemaItem$ = "{50ea08b3-dd1b-4664-9a50-c2f40f4bd79a}"

;- IID_ISchema
#IID_ISchema$ = "{50ea08b4-dd1b-4664-9a50-c2f40f4bd79a}"

;- IID_ISchemaItemCollection
#IID_ISchemaItemCollection$ = "{50ea08b2-dd1b-4664-9a50-c2f40f4bd79a}"

;- IID_ISchemaStringCollection
#IID_ISchemaStringCollection$ = "{50ea08b1-dd1b-4664-9a50-c2f40f4bd79a}"

;- IID_ISchemaType
#IID_ISchemaType$ = "{50ea08b8-dd1b-4664-9a50-c2f40f4bd79a}"

;- IID_ISchemaComplexType
#IID_ISchemaComplexType$ = "{50ea08b9-dd1b-4664-9a50-c2f40f4bd79a}"

;- IID_ISchemaAny
#IID_ISchemaAny$ = "{50ea08bc-dd1b-4664-9a50-c2f40f4bd79a}"

;- IID_ISchemaModelGroup
#IID_ISchemaModelGroup$ = "{50ea08bb-dd1b-4664-9a50-c2f40f4bd79a}"

;- IID_IMXXMLFilter
#IID_IMXXMLFilter$ = "{c90352f7-643c-4fbc-bb23-e996eb2d51fd}"

;- IID_ISchemaAttribute
#IID_ISchemaAttribute$ = "{50ea08b6-dd1b-4664-9a50-c2f40f4bd79a}"

;- IID_ISchemaAttributeGroup
#IID_ISchemaAttributeGroup$ = "{50ea08ba-dd1b-4664-9a50-c2f40f4bd79a}"

;- IID_ISchemaIdentityConstraint
#IID_ISchemaIdentityConstraint$ = "{50ea08bd-dd1b-4664-9a50-c2f40f4bd79a}"

;- IID_ISchemaNotation
#IID_ISchemaNotation$ = "{50ea08be-dd1b-4664-9a50-c2f40f4bd79a}"

;- IID_IXMLDOMSelection
#IID_IXMLDOMSelection$ = "{aa634fc7-5888-44a7-a257-3a47150d3a0e}"

;- Class DOMDocument60
#CLSID_DOMDocument60$ = "{88d96a05-f192-11d4-a65f-0040963251e5}"
;- IID_IXMLDOMDocument3
#IID_IXMLDOMDocument3$ = "{2933bf96-7b36-11d2-b20e-00c04f983e60}"

;- IID_IXMLDOMDocument2
#IID_IXMLDOMDocument2$ = "{2933bf95-7b36-11d2-b20e-00c04f983e60}"

;- IID_IXMLDOMSchemaCollection
#IID_IXMLDOMSchemaCollection$ = "{373984c8-b845-449b-91e7-45ac83036ade}"

;- Class FreeThreadedDOMDocument60
#CLSID_FreeThreadedDOMDocument60$ = "{88d96a06-f192-11d4-a65f-0040963251e5}"
;- Class XMLSchemaCache60
#CLSID_XMLSchemaCache60$ = "{88d96a07-f192-11d4-a65f-0040963251e5}"
;- IID_IXMLDOMSchemaCollection2
#IID_IXMLDOMSchemaCollection2$ = "{50ea08b0-dd1b-4664-9a50-c2f40f4bd79a}"

;- Class XSLTemplate60
#CLSID_XSLTemplate60$ = "{88d96a08-f192-11d4-a65f-0040963251e5}"
;- IID_IXSLTemplate
#IID_IXSLTemplate$ = "{2933bf93-7b36-11d2-b20e-00c04f983e60}"

;- IID_IXSLProcessor
#IID_IXSLProcessor$ = "{2933bf92-7b36-11d2-b20e-00c04f983e60}"

;- Class XMLHTTP60
#CLSID_XMLHTTP60$ = "{88d96a0a-f192-11d4-a65f-0040963251e5}"
;- IID_IXMLHTTPRequest
#IID_IXMLHTTPRequest$ = "{ed8c108d-4349-11d2-91a4-00c04f7969e8}"

;- Class FreeThreadedXMLHTTP60
#CLSID_FreeThreadedXMLHTTP60$ = "{88d96a09-f192-11d4-a65f-0040963251e5}"
;- IID_IXMLHTTPRequest2
#IID_IXMLHTTPRequest2$ = "{e5d37dc0-552a-4d52-9cc0-a14d546fbd04}"

;- IID_IXMLHTTPRequest2Callback
#IID_IXMLHTTPRequest2Callback$ = "{a44a9299-e321-40de-8866-341b41669162}"

;- Class ServerXMLHTTP60
#CLSID_ServerXMLHTTP60$ = "{88d96a0b-f192-11d4-a65f-0040963251e5}"
;- IID_IServerXMLHTTPRequest2
#IID_IServerXMLHTTPRequest2$ = "{2e01311b-c322-4b0a-bd77-b90cfdc8dce7}"

;- IID_IServerXMLHTTPRequest
#IID_IServerXMLHTTPRequest$ = "{2e9196bf-13ba-4dd4-91ca-6c571f281495}"

;- Class SAXXMLReader60
#CLSID_SAXXMLReader60$ = "{88d96a0c-f192-11d4-a65f-0040963251e5}"
;- Class MXXMLWriter60
#CLSID_MXXMLWriter60$ = "{88d96a0f-f192-11d4-a65f-0040963251e5}"
;- IID_IMXWriter
#IID_IMXWriter$ = "{4d7ff4ba-1565-4ea8-94e1-6e724a46f98d}"

;- IID_IVBSAXDeclHandler
#IID_IVBSAXDeclHandler$ = "{e8917260-7579-4be1-b5dd-7afbfa6f077b}"

;- IID_IVBSAXLexicalHandler
#IID_IVBSAXLexicalHandler$ = "{032aac35-8c0e-4d9d-979f-e3b702935576}"

;- Class MXHTMLWriter60
#CLSID_MXHTMLWriter60$ = "{88d96a10-f192-11d4-a65f-0040963251e5}"
;- Class SAXAttributes60
#CLSID_SAXAttributes60$ = "{88d96a0e-f192-11d4-a65f-0040963251e5}"
;- IID_IMXAttributes
#IID_IMXAttributes$ = "{f10d27cc-3ec0-415c-8ed8-77ab1c5e7262}"

;- Class MXNamespaceManager60
#CLSID_MXNamespaceManager60$ = "{88d96a11-f192-11d4-a65f-0040963251e5}"
;- IID_IVBMXNamespaceManager
#IID_IVBMXNamespaceManager$ = "{c90352f5-643c-4fbc-bb23-e996eb2d51fd}"

;- IID_IMXNamespacePrefixes
#IID_IMXNamespacePrefixes$ = "{c90352f4-643c-4fbc-bb23-e996eb2d51fd}"

